In [ ]:
from pathlib import Path
import pandas as pd
import time
pd.set_option("display.max_columns", None) 

ROOT = Path.cwd()

DATA_DIR = ROOT / "parquet"
MLDS_DIR = ROOT / "ml-datasets"
OUTPUT_DIR = ROOT / "output"
LOGS = ROOT / "logs"

LOGS.mkdir(parents=True, exist_ok=True)
OUTPUT_DIR.mkdir(parents=True, exist_ok=True)

In [ ]:
from PyDI.io import load_parquet
import re, unicodedata

metacritic = load_parquet(
    DATA_DIR / "df_metacritic.parquet",
    name="metacritic"
)

playtime = load_parquet(
    DATA_DIR / "df_playtime.parquet",
    name="playtime"
)

vgsales = load_parquet(
  DATA_DIR / "df_videogamesales.parquet",
  name="videogamesales"

)


def normalize_title(text):
    if not isinstance(text, str):
        return ""
    # remove accents/diacritics (ñ -> n)
    text = unicodedata.normalize("NFKD", text).encode("ASCII", "ignore").decode("ASCII")
    cleaned = re.sub(r"[^a-zA-Z0-9]+", " ", text)
    return cleaned.lower().strip()

def generate_blocking_key(title):
    """
    Generate blocking key from first 3 words of title.
    Takes first 2 chars of each word, concatenates
    """
    if not isinstance(title, str):
        return None
    
    tokens = title.split()
    blocking_key = ""
    
    for i in range(min(3, len(tokens))):
        blocking_key += tokens[i][:2]
    
    return blocking_key if blocking_key else None



metacritic["title_norm"] = metacritic["title"].apply(normalize_title)
playtime["title_norm"] = playtime["title"].apply(normalize_title)
vgsales["title_norm"] = vgsales["title"].apply(normalize_title)

metacritic["blocking_key"]=metacritic["title_norm"].apply(generate_blocking_key)
playtime["blocking_key"]=playtime["title_norm"].apply(generate_blocking_key)
vgsales["blocking_key"]=vgsales["title_norm"].apply(generate_blocking_key)

In [5]:
import logging


logging.basicConfig(
    level=logging.INFO,
    format='[%(levelname)-5s] %(name)s - %(message)s',
    handlers=[
          logging.FileHandler(LOGS / 'pydi.log'),
          logging.StreamHandler()
      ],
    force=True
)

### Dataset Summary

In [6]:
from PyDI.profiling import DataProfiler


datasets = [metacritic, playtime, vgsales]
names = ["metacritic", "playtime", "videogamesales"]

# Initialize the DataProfiler
profiler = DataProfiler()

for df, name in zip(datasets, names):
    profile = profiler.summary(df)

display(profile)

metacritic:
  Rows: 14,666
  Columns: 11
  Total nulls: 2,862
  Null percentage: 1.8%
  Null counts per column:
    critic_score: 7 (0.0%)
    user_score: 805 (5.5%)
    esrb_rating: 2,050 (14.0%)

playtime:
  Rows: 84,445
  Columns: 12
  Total nulls: 81,848
  Null percentage: 8.1%
  Null counts per column:
    developer: 9,904 (11.7%)
    publisher: 11,089 (13.1%)
    main_story_hour: 11,924 (14.1%)
    main_plus_sides_hour: 27,132 (32.1%)
    completionist_hour: 21,789 (25.8%)
    blocking_key: 10 (0.0%)

videogamesales:
  Rows: 16,325
  Columns: 13
  Total nulls: 36
  Null percentage: 0.0%
  Null counts per column:
    publisher: 36 (0.2%)

{'rows': 16325,
 'columns': 13,
 'nulls_total': 36,
 'nulls_per_column': {'id': 0,
  'title': 0,
  'platform': 0,
  'release_year': 0,
  'publisher': 36,
  'genres': 0,
  'na_sales_mil': 0,
  'eu_sales_mil': 0,
  'jp_sales_mil': 0,
  'other_sales_mil': 0,
  'global_sales_mil': 0,
  'title_norm': 0,
  'blocking_key': 0},
 'dtypes': {'id': 'object',
  'title': 'object',
  'platform': 'object',
  'release_year': 'float64',
  'publisher': 'object',
  'genres': 'object',
  'na_sales_mil': 'float64',
  'eu_sales_mil': 'float64',
  'jp_sales_mil': 'float64',
  'other_sales_mil': 'float64',
  'global_sales_mil': 'float64',
  'title_norm': 'object',
  'blocking_key': 'object'}}

### Attribute Coverage

In [7]:
coverage = profiler.analyze_coverage(
    datasets=datasets,
    include_samples=True,
    sample_count=3
)

print("📊 Attribute coverage across datasets:")
display(coverage)

# Identify attributes suitable for entity matching
print("\n🔗 Attributes suitable for entity matching:")
matching_attrs = coverage[coverage['datasets_with_attribute'] >= 2]['attribute'].tolist()
print(f"Attributes available in 2+ datasets: {matching_attrs}")

[INFO ] PyDI.fusion.analysis - Analyzed 20 attributes across 3 datasets

📊 Attribute coverage across datasets:

,attribute,metacritic_count,metacritic_pct,metacritic_coverage,metacritic_samples,playtime_count,playtime_pct,playtime_coverage,playtime_samples,videogamesales_count,videogamesales_pct,videogamesales_coverage,videogamesales_samples,avg_coverage,max_coverage,datasets_with_attribute
0,blocking_key,14666/14666,100.0%,1.000000,"['po2', 'megeso', 'redere']",84435/84445,100.0%,0.999882,"['68ihu', 'spma', 'hagu']",16325/16325,100.0%,1.000000,"['wisp', 'sumabr', 'makawi']",0.999961,1.000000,3
1,completionist_hour,0/0,0%,0.000000,N/A,62656/84445,74.2%,0.741974,"[15.83, 18.77, 37.4]",0/0,0%,0.000000,N/A,0.247325,0.741974,1
2,critic_score,14659/14666,100.0%,0.999523,"[95.0, 95.0, 95.0]",0/0,0%,0.000000,N/A,0/0,0%,0.000000,N/A,0.333174,0.999523,1
3,developer,14666/14666,100.0%,1.000000,"['Valve Software', 'Konami', 'Rockstar Games']",74541/84445,88.3%,0.882717,"['Sonalysts', 'Twisted Pixel Games', 'CyberCon...",0/0,0%,0.000000,N/A,0.627572,1.000000,2
4,esrb_rating,12616/14666,86.0%,0.860221,"['E10+', 'M', 'M']",0/0,0%,0.000000,N/A,0/0,0%,0.000000,N/A,0.286740,0.860221,1
5,eu_sales_mil,0/0,0%,0.000000,N/A,0/0,0%,0.000000,N/A,16325/16325,100.0%,1.000000,"[29.02, 3.58, 12.88]",0.333333,1.000000,1
6,genres,14666/14666,100.0%,1.000000,"[array(['Action', 'Shooter', 'First-Person', '...",84445/84445,100.0%,1.000000,"[array(['Simulation'], dtype=object), array(['...",16325/16325,100.0%,1.000000,"[array(['Sports'], dtype=object), array(['Plat...",1.000000,1.000000,3
7,global_sales_mil,0/0,0%,0.000000,N/A,0/0,0%,0.000000,N/A,16325/16325,100.0%,1.000000,"[82.74, 40.24, 35.82]",0.333333,1.000000,1
8,id,14666/14666,100.0%,1.000000,"['metacritic_1', 'metacritic_2', 'metacritic_3']",84445/84445,100.0%,1.000000,"['playtime_1', 'playtime_2', 'playtime_3']",16325/16325,100.0%,1.000000,"['sales_1', 'sales_2', 'sales_3']",1.000000,1.000000,3
9,jp_sales_mil,0/0,0%,0.000000,N/A,0/0,0%,0.000000,N/A,16325/16325,100.0%,1.000000,"[3.77, 6.81, 3.79]",0.333333,1.000000,1
10,main_plus_sides_hour,0/0,0%,0.000000,N/A,57313/84445,67.9%,0.678702,"[35.37, 9.23, 24.5]",0/0,0%,0.000000,N/A,0.226234,0.678702,1
11,main_story_hour,0/0,0%,0.000000,N/A,72521/84445,85.9%,0.858796,"[10.62, 7.6, 18.95]",0/0,0%,0.000000,N/A,0.286265,0.858796,1
12,na_sales_mil,0/0,0%,0.000000,N/A,0/0,0%,0.000000,N/A,16325/16325,100.0%,1.000000,"[41.49, 29.08, 15.85]",0.333333,1.000000,1
13,other_sales_mil,0/0,0%,0.000000,N/A,0/0,0%,0.000000,N/A,16325/16325,100.0%,1.000000,"[8.46, 0.77, 3.31]",0.333333,1.000000,1
14,platform,14666/14666,100.0%,1.000000,"['Xbox 360', 'Xbox One', 'Xbox 360']",84445/84445,100.0%,1.000000,"['PC', 'Xbox 360', 'Nintendo Switch']",16325/16325,100.0%,1.000000,"['Wii', 'NES', 'Wii']",1.000000,1.000000,3
15,publisher,0/0,0%,0.000000,N/A,73356/84445,86.9%,0.868684,"['Electronic Arts', 'Microsoft Games Studios',...",16289/16325,99.8%,0.997795,"['Nintendo', 'Nintendo', 'Nintendo']",0.622160,0.997795,2
16,release_year,14666/14666,100.0%,1.000000,"[2011, 2015, 2010]",84445/84445,100.0%,1.000000,"[1997.0, 2009.0, 2006.0]",16325/16325,100.0%,1.000000,"[2006.0, 1985.0, 2008.0]",1.000000,1.000000,3
17,title,14666/14666,100.0%,1.000000,"['Portal 2', 'Metal Gear Solid V: The Phantom ...",84445/84445,100.0%,1.000000,"['688(I) Hunter/Killer', ""'Splosion Man"", '.ha...",16325/16325,100.0%,1.000000,"['Wii Sports', 'Super Mario Bros.', 'Mario Kar...",1.000000,1.000000,3
18,title_norm,14666/14666,100.0%,1.000000,"['portal 2', 'metal gear solid v the phantom p...",84445/84445,100.0%,1.000000,"['688 i hunter killer', 'splosion man', 'hack ...",16325/16325,100.0%,1.000000,"['wii sports', 'super mario bros', 'mario kart...",1.000000,1.000000,3
19,user_score,13861/14666,94.5%,0.945111,"[8.8, 7.5, 9.0]",0/0,0%,0.000000,N/A,0/0,0%,0.000000,N/A,0.315037,0.945111,1

🔗 Attributes suitable for entity matching:
Attributes available in 2+ datasets: ['blocking_key', 'developer', 'genres', 'id', 'platform', 'publisher', 'release_year', 'title', 'title_norm']

# Entity Matching

In [8]:
BLOCK_EVAL_DIR = OUTPUT_DIR / "blocking_evaluation"
CORR_DIR = OUTPUT_DIR / "correspondences"

BLOCK_EVAL_DIR.mkdir(parents=True, exist_ok=True)
CORR_DIR.mkdir(parents=True, exist_ok=True)

In [10]:
from PyDI.entitymatching import (StandardBlocker,
                                 SortedNeighbourhoodBlocker,
                                 EmbeddingBlocker,
                                 RuleBasedMatcher,
                                 StringComparator,
                                 NumericComparator,
                                 EntityMatchingEvaluator)

In [11]:
train_p2m = load_parquet(
    MLDS_DIR / "train_PM.parquet",
    name="train_playtime_metacritic",
    add_index=False
)

test_p2m = load_parquet(
    MLDS_DIR / "test_PM.parquet",
    name="test_playtime_metacritic",
    add_index=False
)

train_p2s = load_parquet(
    MLDS_DIR / "train_PS.parquet",
    name="train_playtime_sales",
    add_index=False
)

test_p2s = load_parquet(
    MLDS_DIR / "test_PS.parquet",
    name="test_playtime_sales",
    add_index=False
)
train_p2m = train_p2m.rename(columns={"id_left": "id1", "id_right": "id2"})
test_p2m = test_p2m.rename(columns={"id_left": "id1", "id_right": "id2"})
train_p2s = train_p2s.rename(columns={"id_left": "id1", "id_right": "id2"})
test_p2s = test_p2s.rename(columns={"id_left": "id1", "id_right": "id2"})

# Blocking

#### Playtime -> Metacritic

In [14]:
st_blocker_p2m = StandardBlocker(
    playtime, metacritic,
    on=['title_norm'],
    batch_size=1000,
    output_dir=BLOCK_EVAL_DIR,
    id_column='id'
)
st_blocker_p2m_keys=StandardBlocker(
    playtime, metacritic,
    on=['blocking_key'],
    batch_size=1000,
    output_dir=BLOCK_EVAL_DIR,
    id_column='id'
)

sn_blocker_p2m = SortedNeighbourhoodBlocker(
    playtime, metacritic,
    key='title_norm',
    window=20,
    batch_size=750,
    output_dir=BLOCK_EVAL_DIR,
    id_column='id'
)
sn_blocker_p2m_keys = SortedNeighbourhoodBlocker(
    playtime, metacritic,
    key='blocking_key',
    window=20,
    batch_size=750,
    output_dir=BLOCK_EVAL_DIR,
    id_column='id'
)
embedding_blocker_p2m = EmbeddingBlocker(
    playtime, metacritic,
    text_cols=['title_norm', 'platform','release_year'],
    model="sentence-transformers/all-MiniLM-L6-v2",
    index_backend="sklearn",
    top_k=10,
    batch_size=1000,
    threshold=0.6,
    output_dir=BLOCK_EVAL_DIR,
    id_column='id'
)

[INFO ] PyDI.entitymatching.blocking.standard.StandardBlocker - created 42002 blocking keys for first dataset
[INFO ] PyDI.entitymatching.blocking.standard.StandardBlocker - created 9863 blocking keys for second dataset
[INFO ] PyDI.entitymatching.blocking.standard.StandardBlocker - created 6797 blocks from blocking keys
[INFO ] PyDI.entitymatching.blocking.standard.StandardBlocker - Debug results written to file: /Users/onurcanmemis/Desktop/web-data-integration-team-project/output/blocking_evaluation/debugResultsBlocking_StandardBlocker.csv
[INFO ] PyDI.entitymatching.blocking.standard.StandardBlocker - created 27713 blocking keys for first dataset
[INFO ] PyDI.entitymatching.blocking.standard.StandardBlocker - created 6813 blocking keys for second dataset
[INFO ] PyDI.entitymatching.blocking.standard.StandardBlocker - created 5479 blocks from blocking keys
[INFO ] PyDI.entitymatching.blocking.standard.StandardBlocker - Debug results written to file: /Users/onurcanmemis/Desktop/web-data-integration-team-project/output/blocking_evaluation/debugResultsBlocking_StandardBlocker.csv
[INFO ] PyDI.entitymatching.blocking.sorted_neighbourhood.SortedNeighbourhoodBlocker - created sorted neighbourhood with window size 20
[INFO ] PyDI.entitymatching.blocking.sorted_neighbourhood.SortedNeighbourhoodBlocker - created 1 sorted sequence from 99111 records
[INFO ] PyDI.entitymatching.blocking.sorted_neighbourhood.SortedNeighbourhoodBlocker - Debug results written to file: /Users/onurcanmemis/Desktop/web-data-integration-team-project/output/blocking_evaluation/debugResultsBlocking_SortedNeighbourhoodBlocker.csv
[INFO ] PyDI.entitymatching.blocking.sorted_neighbourhood.SortedNeighbourhoodBlocker - created sorted neighbourhood with window size 20
[INFO ] PyDI.entitymatching.blocking.sorted_neighbourhood.SortedNeighbourhoodBlocker - created 1 sorted sequence from 99111 records
[INFO ] PyDI.entitymatching.blocking.sorted_neighbourhood.SortedNeighbourhoodBlocker - Debug results written to file: /Users/onurcanmemis/Desktop/web-data-integration-team-project/output/blocking_evaluation/debugResultsBlocking_SortedNeighbourhoodBlocker.csv
[INFO ] PyDI.entitymatching.blocking.embedding.EmbeddingBlocker - Initialized EmbeddingBlocker with sklearn backend, top_k=10, threshold=0.6

#### Playtime -> Sales

In [15]:
st_blocker_p2s = StandardBlocker(
    playtime, vgsales,
    on=['title_norm'],
    batch_size=1000,
    output_dir=BLOCK_EVAL_DIR,
    id_column='id'
)
st_blocker_p2s_keys=StandardBlocker(
    playtime, vgsales,
    on=['blocking_key'],
    batch_size=1000,
    output_dir=BLOCK_EVAL_DIR,
    id_column='id'
)
sn_blocker_p2s = SortedNeighbourhoodBlocker(
    playtime, vgsales,
    key='title_norm',
    window=20,
    batch_size=750,
    output_dir=BLOCK_EVAL_DIR,
    id_column='id'
)
sn_blocker_p2s_keys = SortedNeighbourhoodBlocker(
    playtime, vgsales,
    key='blocking_key',
    window=20,
    batch_size=750,
    output_dir=BLOCK_EVAL_DIR,
    id_column='id'
)
embedding_blocker_p2s = EmbeddingBlocker(
    playtime, vgsales,
    text_cols=['title_norm', 'platform','release_year'],
    model="sentence-transformers/all-MiniLM-L6-v2",
    index_backend="sklearn",
    top_k=10,
    threshold=0.6,
    batch_size=1000,
    output_dir=BLOCK_EVAL_DIR,
    id_column='id'
)

[INFO ] PyDI.entitymatching.blocking.standard.StandardBlocker - created 42002 blocking keys for first dataset
[INFO ] PyDI.entitymatching.blocking.standard.StandardBlocker - created 11332 blocking keys for second dataset
[INFO ] PyDI.entitymatching.blocking.standard.StandardBlocker - created 5755 blocks from blocking keys
[INFO ] PyDI.entitymatching.blocking.standard.StandardBlocker - Debug results written to file: /Users/onurcanmemis/Desktop/web-data-integration-team-project/output/blocking_evaluation/debugResultsBlocking_StandardBlocker.csv
[INFO ] PyDI.entitymatching.blocking.standard.StandardBlocker - created 27713 blocking keys for first dataset
[INFO ] PyDI.entitymatching.blocking.standard.StandardBlocker - created 8100 blocking keys for second dataset
[INFO ] PyDI.entitymatching.blocking.standard.StandardBlocker - created 5063 blocks from blocking keys
[INFO ] PyDI.entitymatching.blocking.standard.StandardBlocker - Debug results written to file: /Users/onurcanmemis/Desktop/web-data-integration-team-project/output/blocking_evaluation/debugResultsBlocking_StandardBlocker.csv
[INFO ] PyDI.entitymatching.blocking.sorted_neighbourhood.SortedNeighbourhoodBlocker - created sorted neighbourhood with window size 20
[INFO ] PyDI.entitymatching.blocking.sorted_neighbourhood.SortedNeighbourhoodBlocker - created 1 sorted sequence from 100770 records
[INFO ] PyDI.entitymatching.blocking.sorted_neighbourhood.SortedNeighbourhoodBlocker - Debug results written to file: /Users/onurcanmemis/Desktop/web-data-integration-team-project/output/blocking_evaluation/debugResultsBlocking_SortedNeighbourhoodBlocker.csv
[INFO ] PyDI.entitymatching.blocking.sorted_neighbourhood.SortedNeighbourhoodBlocker - created sorted neighbourhood with window size 20
[INFO ] PyDI.entitymatching.blocking.sorted_neighbourhood.SortedNeighbourhoodBlocker - created 1 sorted sequence from 100770 records
[INFO ] PyDI.entitymatching.blocking.sorted_neighbourhood.SortedNeighbourhoodBlocker - Debug results written to file: /Users/onurcanmemis/Desktop/web-data-integration-team-project/output/blocking_evaluation/debugResultsBlocking_SortedNeighbourhoodBlocker.csv
[INFO ] PyDI.entitymatching.blocking.embedding.EmbeddingBlocker - Initialized EmbeddingBlocker with sklearn backend, top_k=10, threshold=0.6

In [16]:
block_times = []   # will store timing info here

def run_blocker(name, blocker):
    """
    Returns the candidates dataframe.
    """
    start = time.time()
    candidates = blocker.materialize()
    elapsed = time.time() - start

    block_times.append({
        "blocker": name,
        "time_sec": elapsed,
        "n_candidates": len(candidates)
    })

    print(f"{name} finished in {elapsed:.2f}s with {len(candidates)} pairs")
    return candidates

# ---- P2M ----
standard_candidates_p2m       = run_blocker("StandardBlocker_p2m",        st_blocker_p2m)
standard_candidates_p2m_keys  = run_blocker("StandardBlocker_p2m_keys",   st_blocker_p2m_keys)

sn_candidates_p2m             = run_blocker("SortedNeighbourhood_p2m",    sn_blocker_p2m)
sn_candidates_p2m_keys        = run_blocker("SortedNeighbourhood_p2m_keys", sn_blocker_p2m_keys)

embedding_candidates_p2m      = run_blocker("EmbeddingBlocker_p2m",       embedding_blocker_p2m)

# ---- P2S ----
standard_candidates_p2s       = run_blocker("StandardBlocker_p2s",        st_blocker_p2s)
standard_candidates_p2s_keys  = run_blocker("StandardBlocker_p2s_keys",   st_blocker_p2s_keys)

sn_candidates_p2s             = run_blocker("SortedNeighbourhood_p2s",    sn_blocker_p2s)
sn_candidates_p2s_keys        = run_blocker("SortedNeighbourhood_p2s_keys", sn_blocker_p2s_keys)

embedding_candidates_p2s      = run_blocker("EmbeddingBlocker_p2s",       embedding_blocker_p2s)

StandardBlocker_p2m finished in 0.03s with 36146 pairs
StandardBlocker_p2m_keys finished in 0.09s with 297610 pairs

[INFO ] sentence_transformers.SentenceTransformer - Use pytorch device_name: mps
[INFO ] sentence_transformers.SentenceTransformer - Load pretrained SentenceTransformer: sentence-transformers/all-MiniLM-L6-v2

SortedNeighbourhood_p2m finished in 0.18s with 466954 pairs
SortedNeighbourhood_p2m_keys finished in 0.17s with 440621 pairs

[INFO ] PyDI.entitymatching.blocking.embedding.EmbeddingBlocker - Loaded sentence transformer model: sentence-transformers/all-MiniLM-L6-v2
[INFO ] PyDI.entitymatching.blocking.embedding.EmbeddingBlocker - created 384d embeddings for first dataset
[INFO ] PyDI.entitymatching.blocking.embedding.EmbeddingBlocker - created 384d embeddings for second dataset
[INFO ] PyDI.entitymatching.blocking.embedding.EmbeddingBlocker - created similarity index with 14666 vectors, metric=cosine
[INFO ] PyDI.entitymatching.blocking.embedding.EmbeddingBlocker - Debug results written to file: /Users/onurcanmemis/Desktop/web-data-integration-team-project/output/blocking_evaluation/debugResultsBlocking_EmbeddingBlocker.csv

EmbeddingBlocker_p2m finished in 87.17s with 453398 pairs
StandardBlocker_p2s finished in 0.01s with 29909 pairs
StandardBlocker_p2s_keys finished in 0.06s with 235163 pairs

[INFO ] sentence_transformers.SentenceTransformer - Use pytorch device_name: mps
[INFO ] sentence_transformers.SentenceTransformer - Load pretrained SentenceTransformer: sentence-transformers/all-MiniLM-L6-v2

SortedNeighbourhood_p2s finished in 0.19s with 483276 pairs
SortedNeighbourhood_p2s_keys finished in 0.17s with 469594 pairs

[INFO ] PyDI.entitymatching.blocking.embedding.EmbeddingBlocker - Loaded sentence transformer model: sentence-transformers/all-MiniLM-L6-v2
[INFO ] PyDI.entitymatching.blocking.embedding.EmbeddingBlocker - created 384d embeddings for first dataset
[INFO ] PyDI.entitymatching.blocking.embedding.EmbeddingBlocker - created 384d embeddings for second dataset
[INFO ] PyDI.entitymatching.blocking.embedding.EmbeddingBlocker - created similarity index with 16325 vectors, metric=cosine
[INFO ] PyDI.entitymatching.blocking.embedding.EmbeddingBlocker - Debug results written to file: /Users/onurcanmemis/Desktop/web-data-integration-team-project/output/blocking_evaluation/debugResultsBlocking_EmbeddingBlocker.csv

EmbeddingBlocker_p2s finished in 86.78s with 378750 pairs

In [17]:
block_times_df = pd.DataFrame(block_times).sort_values("time_sec")
display(block_times_df)

                        blocker   time_sec  n_candidates
5           StandardBlocker_p2s   0.011348         29909
0           StandardBlocker_p2m   0.032423         36146
6      StandardBlocker_p2s_keys   0.059442        235163
1      StandardBlocker_p2m_keys   0.086915        297610
3  SortedNeighbourhood_p2m_keys   0.169630        440621
8  SortedNeighbourhood_p2s_keys   0.173567        469594
2       SortedNeighbourhood_p2m   0.176042        466954
7       SortedNeighbourhood_p2s   0.185978        483276
9          EmbeddingBlocker_p2s  86.784082        378750
4          EmbeddingBlocker_p2m  87.169982        453398

## Evaluate Blocking

### Playtime -> Metacritic

In [ ]:
evaluator = EntityMatchingEvaluator()

p2m_blocking_candidates = {
    'StandardBlocking': [standard_candidates_p2m, st_blocker_p2m], #0.947
    'StandardBlocking_keys': [standard_candidates_p2m_keys, st_blocker_p2m_keys], # 0.979
    'SortedNeighbourhoodBlocker': [sn_candidates_p2m, sn_blocker_p2m], #0.992
    'SortedNeighbourhoodBlocker_keys': [sn_candidates_p2m_keys, sn_blocker_p2m_keys], #0.789
    'EmbeddingBlocking': [embedding_candidates_p2m, embedding_blocker_p2m] #0.997
}

In [19]:
p2m_results = []
for method_name, candidates in p2m_blocking_candidates.items():
    result = evaluator.evaluate_blocking(candidates[0],
                                         train_p2m,
                                         candidates[1],
                                         out_dir=BLOCK_EVAL_DIR)
    result['method'] = method_name
    result['dataset'] = 'p2m'
    p2m_results.append(result)

p2m_best = max(p2m_results, key=lambda x: (x['pair_completeness'], x['reduction_ratio']))
print(f"Best blocking for p2m: {p2m_best['method']} (PC: {p2m_best['pair_completeness']:.3f}, RR: {p2m_best['reduction_ratio']:.3f})")

[INFO ] root -   Pair Completeness: 0.947
[INFO ] root -   Pair Quality:      0.010
[INFO ] root -   Reduction Ratio:   0.999971
[INFO ] root -   True Matches Found: 354/374
[INFO ] root - Blocking evaluation complete!
[INFO ] root -   Pair Completeness: 0.979
[INFO ] root -   Pair Quality:      0.001
[INFO ] root -   Reduction Ratio:   0.999760
[INFO ] root -   True Matches Found: 366/374
[INFO ] root - Blocking evaluation complete!
[INFO ] root -   Pair Completeness: 0.992
[INFO ] root -   Pair Quality:      0.001
[INFO ] root -   Reduction Ratio:   0.999623
[INFO ] root -   True Matches Found: 371/374
[INFO ] root - Blocking evaluation complete!
[INFO ] root -   Pair Completeness: 0.789
[INFO ] root -   Pair Quality:      0.001
[INFO ] root -   Reduction Ratio:   0.999644
[INFO ] root -   True Matches Found: 295/374
[INFO ] root - Blocking evaluation complete!
[INFO ] root -   Pair Completeness: 0.997
[INFO ] root -   Pair Quality:      0.001
[INFO ] root -   Reduction Ratio:   0.999634
[INFO ] root -   True Matches Found: 373/374
[INFO ] root - Blocking evaluation complete!

Best blocking for p2m: EmbeddingBlocking (PC: 0.997, RR: 1.000)

### Playtime -> Sales

In [ ]:
p2s_blocking_candidates = {
    'StandardBlocking': [standard_candidates_p2s, st_blocker_p2s], # 0.749
    'StandardBlocking_keys': [standard_candidates_p2s_keys, st_blocker_p2s_keys], # 0.850
    'SortedNeighbourhoodBlocker': [sn_candidates_p2s, sn_blocker_p2s], # 0.897
    'SortedNeighbourhoodBlocker_keys': [sn_candidates_p2s_keys, sn_blocker_p2s_keys], #.702
    'EmbeddingBlocking': [embedding_candidates_p2s, embedding_blocker_p2s] #0.960
}

In [21]:
p2s_results = []
for method_name, candidates in p2s_blocking_candidates.items():
    result = evaluator.evaluate_blocking(candidates[0],
                                         train_p2s,
                                         candidates[1],
                                         out_dir=BLOCK_EVAL_DIR)
    result['method'] = method_name
    result['dataset'] = 'p2m'
    p2s_results.append(result)

p2s_best = max(p2s_results, key=lambda x: (x['pair_completeness'], x['reduction_ratio']))
print(f"Best blocking for p2s: {p2s_best['method']} (PC: {p2s_best['pair_completeness']:.3f}, RR: {p2s_best['reduction_ratio']:.3f})")

[INFO ] root -   Pair Completeness: 0.749
[INFO ] root -   Pair Quality:      0.009
[INFO ] root -   Reduction Ratio:   0.999978
[INFO ] root -   True Matches Found: 284/379
[INFO ] root - Blocking evaluation complete!
[INFO ] root -   Pair Completeness: 0.850
[INFO ] root -   Pair Quality:      0.001
[INFO ] root -   Reduction Ratio:   0.999829
[INFO ] root -   True Matches Found: 322/379
[INFO ] root - Blocking evaluation complete!
[INFO ] root -   Pair Completeness: 0.897
[INFO ] root -   Pair Quality:      0.001
[INFO ] root -   Reduction Ratio:   0.999649
[INFO ] root -   True Matches Found: 340/379
[INFO ] root - Blocking evaluation complete!
[INFO ] root -   Pair Completeness: 0.702
[INFO ] root -   Pair Quality:      0.001
[INFO ] root -   Reduction Ratio:   0.999659
[INFO ] root -   True Matches Found: 266/379
[INFO ] root - Blocking evaluation complete!
[INFO ] root -   Pair Completeness: 0.960
[INFO ] root -   Pair Quality:      0.001
[INFO ] root -   Reduction Ratio:   0.999725
[INFO ] root -   True Matches Found: 364/379
[INFO ] root - Blocking evaluation complete!

Best blocking for p2s: EmbeddingBlocking (PC: 0.960, RR: 1.000)

# Matchers

## Rule Based Matcher

In [110]:
common_comparators= [   
    StringComparator(
        column='title_norm',
        similarity_function='jaro_winkler'
    ),
    StringComparator(
        column='platform',
        similarity_function='jaccard',
        preprocess=str.lower
    ),
    NumericComparator(
    column="release_year",
    method="absolute_difference",
)]
comparators_p2m = common_comparators + [
    StringComparator(
        column='developer',
        similarity_function='jaro_winkler',
        preprocess=str.lower
    )
]
comparators_p2s= common_comparators + [
    StringComparator(
        column='publisher',
        similarity_function='jaro_winkler',
        preprocess=str.lower
    )
]

In [111]:
matcher = RuleBasedMatcher()

correspondences_p2m,debug_p2m = matcher.match(
    df_left=playtime,
    df_right=metacritic, 
    candidates=embedding_candidates_p2m,
    comparators=comparators_p2m,
    weights=[0.5, 0.2, 0.2, 0.1],
    threshold=0.80,
    id_column='id',
    debug=True
)

correspondences_p2s,debug_p2s = matcher.match(
    df_left=playtime,
    df_right=vgsales, 
    candidates=embedding_candidates_p2s,
    comparators=comparators_p2s,
    weights=[0.5, 0.2, 0.2, 0.1],
    threshold=0.80,
    id_column='id',
    debug=True
)

[INFO ] PyDI.entitymatching.rule_based.RuleBasedMatcher - Starting Entity Matching
[INFO ] PyDI.entitymatching.rule_based.RuleBasedMatcher - Blocking 84445 x 14666 elements
[INFO ] PyDI.entitymatching.rule_based.RuleBasedMatcher - Matching 84445 x 14666 elements after 0:00:0.019; 453398 blocked pairs (reduction ratio: 0.9996339048466698)
[INFO ] PyDI.entitymatching.rule_based.RuleBasedMatcher - Entity Matching finished after 0:00:46.525; found 20447 correspondences.
[INFO ] PyDI.entitymatching.rule_based.RuleBasedMatcher - Starting Entity Matching
[INFO ] PyDI.entitymatching.rule_based.RuleBasedMatcher - Blocking 84445 x 16325 elements
[INFO ] PyDI.entitymatching.rule_based.RuleBasedMatcher - Matching 84445 x 16325 elements after 0:00:0.022; 378750 blocked pairs (reduction ratio: 0.9997252577114403)
[INFO ] PyDI.entitymatching.rule_based.RuleBasedMatcher - Entity Matching finished after 0:00:37.658; found 18182 correspondences.

In [66]:
cluster_analysis_dir = OUTPUT_DIR / "cluster_analysis"
cluster_analysis_dir.mkdir(parents=True, exist_ok=True)
cluster_distribution_p2m_rb_1 = EntityMatchingEvaluator.create_cluster_size_distribution(
    correspondences=correspondences_p2m,
    out_dir=cluster_analysis_dir
)
cluster_distribution_p2s_rb_1 = EntityMatchingEvaluator.create_cluster_size_distribution(
    correspondences=correspondences_p2s,
    out_dir=cluster_analysis_dir
)

[INFO ] PyDI.entitymatching.evaluation - Cluster Size Distribution of 8750 clusters:
[INFO ] PyDI.entitymatching.evaluation - 	Cluster Size	| Frequency	| Percentage
[INFO ] PyDI.entitymatching.evaluation - 	──────────────────────────────────────────────────
[INFO ] PyDI.entitymatching.evaluation - 		2	|	6089	|	69.59%
[INFO ] PyDI.entitymatching.evaluation - 		3	|	1199	|	13.70%
[INFO ] PyDI.entitymatching.evaluation - 		4	|	596	|	6.81%
[INFO ] PyDI.entitymatching.evaluation - 		5	|	255	|	2.91%
[INFO ] PyDI.entitymatching.evaluation - 		6	|	193	|	2.21%
[INFO ] PyDI.entitymatching.evaluation - 		7	|	90	|	1.03%
[INFO ] PyDI.entitymatching.evaluation - 		8	|	71	|	0.81%
[INFO ] PyDI.entitymatching.evaluation - 		9	|	50	|	0.57%
[INFO ] PyDI.entitymatching.evaluation - 		10	|	38	|	0.43%
[INFO ] PyDI.entitymatching.evaluation - 		11	|	27	|	0.31%
[INFO ] PyDI.entitymatching.evaluation - 		12	|	28	|	0.32%
[INFO ] PyDI.entitymatching.evaluation - 		13	|	17	|	0.19%
[INFO ] PyDI.entitymatching.evaluation - 		14	|	16	|	0.18%
[INFO ] PyDI.entitymatching.evaluation - 		15	|	9	|	0.10%
[INFO ] PyDI.entitymatching.evaluation - 		16	|	10	|	0.11%
[INFO ] PyDI.entitymatching.evaluation - 		17	|	6	|	0.07%
[INFO ] PyDI.entitymatching.evaluation - 		18	|	6	|	0.07%
[INFO ] PyDI.entitymatching.evaluation - 		19	|	1	|	0.01%
[INFO ] PyDI.entitymatching.evaluation - 		20	|	5	|	0.06%
[INFO ] PyDI.entitymatching.evaluation - 		21	|	5	|	0.06%
[INFO ] PyDI.entitymatching.evaluation - 		22	|	1	|	0.01%
[INFO ] PyDI.entitymatching.evaluation - 		23	|	2	|	0.02%
[INFO ] PyDI.entitymatching.evaluation - 		25	|	1	|	0.01%
[INFO ] PyDI.entitymatching.evaluation - 		26	|	2	|	0.02%
[INFO ] PyDI.entitymatching.evaluation - 		27	|	5	|	0.06%
[INFO ] PyDI.entitymatching.evaluation - 		28	|	2	|	0.02%
[INFO ] PyDI.entitymatching.evaluation - 		29	|	1	|	0.01%
[INFO ] PyDI.entitymatching.evaluation - 		30	|	1	|	0.01%
[INFO ] PyDI.entitymatching.evaluation - 		31	|	2	|	0.02%
[INFO ] PyDI.entitymatching.evaluation - 		32	|	1	|	0.01%
[INFO ] PyDI.entitymatching.evaluation - 		33	|	1	|	0.01%
[INFO ] PyDI.entitymatching.evaluation - 		37	|	3	|	0.03%
[INFO ] PyDI.entitymatching.evaluation - 		38	|	1	|	0.01%
[INFO ] PyDI.entitymatching.evaluation - 		40	|	1	|	0.01%
[INFO ] PyDI.entitymatching.evaluation - 		44	|	1	|	0.01%
[INFO ] PyDI.entitymatching.evaluation - 		46	|	1	|	0.01%
[INFO ] PyDI.entitymatching.evaluation - 		51	|	2	|	0.02%
[INFO ] PyDI.entitymatching.evaluation - 		53	|	1	|	0.01%
[INFO ] PyDI.entitymatching.evaluation - 		54	|	1	|	0.01%
[INFO ] PyDI.entitymatching.evaluation - 		56	|	2	|	0.02%
[INFO ] PyDI.entitymatching.evaluation - 		58	|	1	|	0.01%
[INFO ] PyDI.entitymatching.evaluation - 		65	|	1	|	0.01%
[INFO ] PyDI.entitymatching.evaluation - 		66	|	1	|	0.01%
[INFO ] PyDI.entitymatching.evaluation - 		86	|	1	|	0.01%
[INFO ] PyDI.entitymatching.evaluation - 		172	|	1	|	0.01%
[INFO ] PyDI.entitymatching.evaluation - 		199	|	1	|	0.01%
[INFO ] PyDI.entitymatching.evaluation - 		306	|	1	|	0.01%
[INFO ] root - Cluster size distribution written to /Users/onurcanmemis/Desktop/web-data-integration-team-project/output/cluster_analysis/cluster_size_distribution.csv
[INFO ] PyDI.entitymatching.evaluation - Cluster Size Distribution of 4893 clusters:
[INFO ] PyDI.entitymatching.evaluation - 	Cluster Size	| Frequency	| Percentage
[INFO ] PyDI.entitymatching.evaluation - 	──────────────────────────────────────────────────
[INFO ] PyDI.entitymatching.evaluation - 		2	|	3047	|	62.27%
[INFO ] PyDI.entitymatching.evaluation - 		3	|	605	|	12.36%
[INFO ] PyDI.entitymatching.evaluation - 		4	|	422	|	8.62%
[INFO ] PyDI.entitymatching.evaluation - 		5	|	203	|	4.15%
[INFO ] PyDI.entitymatching.evaluation - 		6	|	163	|	3.33%
[INFO ] PyDI.entitymatching.evaluation - 		7	|	98	|	2.00%
[INFO ] PyDI.entitymatching.evaluation - 		8	|	59	|	1.21%
[INFO ] PyDI.entitymatching.evaluation - 		9	|	45	|	0.92%
[INFO ] PyDI.entitymatching.evaluation - 		10	|	31	|	0.63%
[INFO ] PyDI.entitymatching.evaluation - 		11	|	21	|	0.43%
[INFO ] PyDI.entitymatching.evaluation - 		12	|	18	|	0.37%
[INFO ] PyDI.entitymatching.evaluation - 		13	|	18	|	0.37%
[INFO ] PyDI.entitymatching.evaluation - 		14	|	17	|	0.35%
[INFO ] PyDI.entitymatching.evaluation - 		15	|	9	|	0.18%
[INFO ] PyDI.entitymatching.evaluation - 		16	|	16	|	0.33%
[INFO ] PyDI.entitymatching.evaluation - 		17	|	14	|	0.29%
[INFO ] PyDI.entitymatching.evaluation - 		18	|	11	|	0.22%
[INFO ] PyDI.entitymatching.evaluation - 		19	|	6	|	0.12%
[INFO ] PyDI.entitymatching.evaluation - 		20	|	8	|	0.16%
[INFO ] PyDI.entitymatching.evaluation - 		21	|	8	|	0.16%
[INFO ] PyDI.entitymatching.evaluation - 		22	|	6	|	0.12%
[INFO ] PyDI.entitymatching.evaluation - 		23	|	3	|	0.06%
[INFO ] PyDI.entitymatching.evaluation - 		24	|	4	|	0.08%
[INFO ] PyDI.entitymatching.evaluation - 		25	|	1	|	0.02%
[INFO ] PyDI.entitymatching.evaluation - 		26	|	6	|	0.12%
[INFO ] PyDI.entitymatching.evaluation - 		27	|	1	|	0.02%
[INFO ] PyDI.entitymatching.evaluation - 		28	|	4	|	0.08%
[INFO ] PyDI.entitymatching.evaluation - 		29	|	8	|	0.16%
[INFO ] PyDI.entitymatching.evaluation - 		30	|	5	|	0.10%
[INFO ] PyDI.entitymatching.evaluation - 		31	|	1	|	0.02%
[INFO ] PyDI.entitymatching.evaluation - 		34	|	3	|	0.06%
[INFO ] PyDI.entitymatching.evaluation - 		35	|	4	|	0.08%
[INFO ] PyDI.entitymatching.evaluation - 		36	|	2	|	0.04%
[INFO ] PyDI.entitymatching.evaluation - 		37	|	1	|	0.02%
[INFO ] PyDI.entitymatching.evaluation - 		38	|	2	|	0.04%
[INFO ] PyDI.entitymatching.evaluation - 		39	|	2	|	0.04%
[INFO ] PyDI.entitymatching.evaluation - 		40	|	2	|	0.04%
[INFO ] PyDI.entitymatching.evaluation - 		41	|	3	|	0.06%
[INFO ] PyDI.entitymatching.evaluation - 		43	|	1	|	0.02%
[INFO ] PyDI.entitymatching.evaluation - 		48	|	3	|	0.06%
[INFO ] PyDI.entitymatching.evaluation - 		49	|	1	|	0.02%
[INFO ] PyDI.entitymatching.evaluation - 		50	|	1	|	0.02%
[INFO ] PyDI.entitymatching.evaluation - 		56	|	1	|	0.02%
[INFO ] PyDI.entitymatching.evaluation - 		59	|	1	|	0.02%
[INFO ] PyDI.entitymatching.evaluation - 		60	|	1	|	0.02%
[INFO ] PyDI.entitymatching.evaluation - 		63	|	1	|	0.02%
[INFO ] PyDI.entitymatching.evaluation - 		64	|	1	|	0.02%
[INFO ] PyDI.entitymatching.evaluation - 		71	|	1	|	0.02%
[INFO ] PyDI.entitymatching.evaluation - 		84	|	1	|	0.02%
[INFO ] PyDI.entitymatching.evaluation - 		91	|	1	|	0.02%
[INFO ] PyDI.entitymatching.evaluation - 		112	|	1	|	0.02%
[INFO ] PyDI.entitymatching.evaluation - 		310	|	1	|	0.02%
[INFO ] root - Cluster size distribution written to /Users/onurcanmemis/Desktop/web-data-integration-team-project/output/cluster_analysis/cluster_size_distribution.csv

In [ ]:
print(f"\n📊 Cluster Size Distribution Results (Playtime -> Metacritic):")
display(cluster_distribution_p2m_rb_1)
print(f"\n📊 Cluster Size Distribution Results (Playtime -> VGSales):")
display(cluster_distribution_p2s_rb_1)

📊 Cluster Size Distribution Results (Playtime -> Metacritic):

    cluster_size  frequency  percentage
0              2       6089   69.588571
1              3       1199   13.702857
2              4        596    6.811429
3              5        255    2.914286
4              6        193    2.205714
5              7         90    1.028571
6              8         71    0.811429
7              9         50    0.571429
8             10         38    0.434286
9             11         27    0.308571
10            12         28    0.320000
11            13         17    0.194286
12            14         16    0.182857
13            15          9    0.102857
14            16         10    0.114286
15            17          6    0.068571
16            18          6    0.068571
17            19          1    0.011429
18            20          5    0.057143
19            21          5    0.057143
20            22          1    0.011429
21            23          2    0.022857
22            25          1    0.011429
23            26          2    0.022857
24            27          5    0.057143
25            28          2    0.022857
26            29          1    0.011429
27            30          1    0.011429
28            31          2    0.022857
29            32          1    0.011429
30            33          1    0.011429
31            37          3    0.034286
32            38          1    0.011429
33            40          1    0.011429
34            44          1    0.011429
35            46          1    0.011429
36            51          2    0.022857
37            53          1    0.011429
38            54          1    0.011429
39            56          2    0.022857
40            58          1    0.011429
41            65          1    0.011429
42            66          1    0.011429
43            86          1    0.011429
44           172          1    0.011429
45           199          1    0.011429
46           306          1    0.011429

📊 Cluster Size Distribution Results (Playtime -> VGSales):

    cluster_size  frequency  percentage
0              2       3047   62.272634
1              3        605   12.364602
2              4        422    8.624566
3              5        203    4.148784
4              6        163    3.331290
5              7         98    2.002861
6              8         59    1.205804
7              9         45    0.919681
8             10         31    0.633558
9             11         21    0.429185
10            12         18    0.367872
11            13         18    0.367872
12            14         17    0.347435
13            15          9    0.183936
14            16         16    0.326998
15            17         14    0.286123
16            18         11    0.224811
17            19          6    0.122624
18            20          8    0.163499
19            21          8    0.163499
20            22          6    0.122624
21            23          3    0.061312
22            24          4    0.081749
23            25          1    0.020437
24            26          6    0.122624
25            27          1    0.020437
26            28          4    0.081749
27            29          8    0.163499
28            30          5    0.102187
29            31          1    0.020437
30            34          3    0.061312
31            35          4    0.081749
32            36          2    0.040875
33            37          1    0.020437
34            38          2    0.040875
35            39          2    0.040875
36            40          2    0.040875
37            41          3    0.061312
38            43          1    0.020437
39            48          3    0.061312
40            49          1    0.020437
41            50          1    0.020437
42            56          1    0.020437
43            59          1    0.020437
44            60          1    0.020437
45            63          1    0.020437
46            64          1    0.020437
47            71          1    0.020437
48            84          1    0.020437
49            91          1    0.020437
50           112          1    0.020437
51           310          1    0.020437

### RB Matching Evaluation
#### Playtime -> Metacritic

In [26]:
debug_output_dir = OUTPUT_DIR / "debug_results_entity_matching"
debug_output_dir.mkdir(parents=True, exist_ok=True)

eval_results_p2m = EntityMatchingEvaluator.evaluate_matching(
    correspondences=correspondences_p2m,
    test_pairs=test_p2m,
    out_dir=debug_output_dir
)

display(eval_results_p2m)

[INFO ] root - Confusion Matrix:
[INFO ] root -   True Positives:  93
[INFO ] root -   True Negatives:  49
[INFO ] root -   False Positives: 6
[INFO ] root -   False Negatives: 0
[INFO ] root - Performance Metrics:
[INFO ] root -   Accuracy:  0.959
[INFO ] root -   Precision: 0.939
[INFO ] root -   Recall:    1.000
[INFO ] root -   F1-Score:  0.969

{'precision': 0.9393939393939394,
 'recall': 1.0,
 'f1': 0.96875,
 'accuracy': 0.9594594594594594,
 'true_positives': 93,
 'false_positives': 6,
 'false_negatives': 0,
 'true_negatives': 49,
 'threshold_used': 0.0,
 'total_correspondences': 20447,
 'filtered_correspondences': 20447,
 'evaluation_timestamp': '2025-11-29T13:46:12.108197',
 'output_files': ['/Users/onurcanmemis/Desktop/web-data-integration-team-project/output/debug_results_entity_matching/matching_evaluation_summary.json',
  '/Users/onurcanmemis/Desktop/web-data-integration-team-project/output/debug_results_entity_matching/matching_detailed_results.csv']}

#### Playtime -> Sales

In [27]:
eval_results_p2s = EntityMatchingEvaluator.evaluate_matching(
    correspondences=correspondences_p2s,
    test_pairs=test_p2s,
    out_dir=debug_output_dir
)

display(eval_results_p2s)

[INFO ] root - Confusion Matrix:
[INFO ] root -   True Positives:  91
[INFO ] root -   True Negatives:  50
[INFO ] root -   False Positives: 4
[INFO ] root -   False Negatives: 4
[INFO ] root - Performance Metrics:
[INFO ] root -   Accuracy:  0.946
[INFO ] root -   Precision: 0.958
[INFO ] root -   Recall:    0.958
[INFO ] root -   F1-Score:  0.958

{'precision': 0.9578947368421052,
 'recall': 0.9578947368421052,
 'f1': 0.9578947368421052,
 'accuracy': 0.9463087248322147,
 'true_positives': 91,
 'false_positives': 4,
 'false_negatives': 4,
 'true_negatives': 50,
 'threshold_used': 0.0,
 'total_correspondences': 18182,
 'filtered_correspondences': 18182,
 'evaluation_timestamp': '2025-11-29T13:46:27.504521',
 'output_files': ['/Users/onurcanmemis/Desktop/web-data-integration-team-project/output/debug_results_entity_matching/matching_evaluation_summary.json',
  '/Users/onurcanmemis/Desktop/web-data-integration-team-project/output/debug_results_entity_matching/matching_detailed_results.csv']}

In [112]:
from PyDI.entitymatching import MaximumBipartiteMatching, StableMatching

# We are using Maxmimum Bipartite Matching to refine results to 1:1 matches
clusterer = MaximumBipartiteMatching()
mbm_correspondences_p2m = clusterer.cluster(correspondences_p2m)
mbm_correspondences_p2s = clusterer.cluster(correspondences_p2s)

[INFO ] root - Filtered correspondences: 20447 -> 20447 (threshold=0.0)
[INFO ] root - Maximum bipartite matching: 20447 -> 11314
[INFO ] root - MaximumBipartiteMatching: 20447 -> 11314 correspondences
[INFO ] root - MaximumBipartiteMatching: 26501 -> 22628 entities
[INFO ] root - Filtered correspondences: 18182 -> 18182 (threshold=0.0)
[INFO ] root - Maximum bipartite matching: 18182 -> 8000
[INFO ] root - MaximumBipartiteMatching: 18182 -> 8000 correspondences
[INFO ] root - MaximumBipartiteMatching: 18645 -> 16000 entities

In [113]:
eval_p2m = EntityMatchingEvaluator.evaluate_matching(
                correspondences=mbm_correspondences_p2m,
                test_pairs=test_p2m,
                out_dir=BLOCK_EVAL_DIR,
            )

display(eval_p2m)

[INFO ] root - Confusion Matrix:
[INFO ] root -   True Positives:  77
[INFO ] root -   True Negatives:  54
[INFO ] root -   False Positives: 1
[INFO ] root -   False Negatives: 16
[INFO ] root - Performance Metrics:
[INFO ] root -   Accuracy:  0.885
[INFO ] root -   Precision: 0.987
[INFO ] root -   Recall:    0.828
[INFO ] root -   F1-Score:  0.901

{'precision': 0.9871794871794872,
 'recall': 0.8279569892473119,
 'f1': 0.9005847953216375,
 'accuracy': 0.8851351351351351,
 'true_positives': 77,
 'false_positives': 1,
 'false_negatives': 16,
 'true_negatives': 54,
 'threshold_used': 0.0,
 'total_correspondences': 11314,
 'filtered_correspondences': 11314,
 'evaluation_timestamp': '2025-11-29T16:01:23.441781',
 'output_files': ['/Users/onurcanmemis/Desktop/web-data-integration-team-project/output/blocking_evaluation/matching_evaluation_summary.json',
  '/Users/onurcanmemis/Desktop/web-data-integration-team-project/output/blocking_evaluation/matching_detailed_results.csv']}

In [114]:
eval_p2s = EntityMatchingEvaluator.evaluate_matching(
                correspondences=mbm_correspondences_p2s,
                test_pairs=test_p2s,
                out_dir=BLOCK_EVAL_DIR,
            )

display(eval_p2s)

[INFO ] root - Confusion Matrix:
[INFO ] root -   True Positives:  66
[INFO ] root -   True Negatives:  54
[INFO ] root -   False Positives: 0
[INFO ] root -   False Negatives: 29
[INFO ] root - Performance Metrics:
[INFO ] root -   Accuracy:  0.805
[INFO ] root -   Precision: 1.000
[INFO ] root -   Recall:    0.695
[INFO ] root -   F1-Score:  0.820

{'precision': 1.0,
 'recall': 0.6947368421052632,
 'f1': 0.8198757763975156,
 'accuracy': 0.8053691275167785,
 'true_positives': 66,
 'false_positives': 0,
 'false_negatives': 29,
 'true_negatives': 54,
 'threshold_used': 0.0,
 'total_correspondences': 8000,
 'filtered_correspondences': 8000,
 'evaluation_timestamp': '2025-11-29T16:01:23.855822',
 'output_files': ['/Users/onurcanmemis/Desktop/web-data-integration-team-project/output/blocking_evaluation/matching_evaluation_summary.json',
  '/Users/onurcanmemis/Desktop/web-data-integration-team-project/output/blocking_evaluation/matching_detailed_results.csv']}

## Rule Based Matcher_Optimized

In [100]:
common_comparators= [   
    StringComparator(
        column='title_norm',
        similarity_function='cosine'
    ),
    StringComparator(
        column='platform',
        similarity_function='identity',
        preprocess=str.lower
    ),
    NumericComparator(
    column="release_year",
    method="within_range",
    max_difference=0,   # exact match only
)]
comparators_p2m = common_comparators + [
    StringComparator(
        column='developer',
        similarity_function='cosine',
        preprocess=str.lower
    )
]
comparators_p2s= common_comparators + [
    StringComparator(
        column='publisher',
        similarity_function='cosine',
        preprocess=str.lower
    )
]

In [101]:
matcher = RuleBasedMatcher()

correspondences_p2m = matcher.match(
    df_left=playtime,
    df_right=metacritic, 
    candidates=embedding_candidates_p2m,
    comparators=comparators_p2m,
    weights=[0.5, 0.2, 0.2, 0.1],
    threshold=0.80,
    id_column='id',
)

correspondences_p2s = matcher.match(
    df_left=playtime,
    df_right=vgsales, 
    candidates=embedding_candidates_p2s,
    comparators=comparators_p2s,
    weights=[0.5, 0.2, 0.2, 0.1],
    threshold=0.80,
    id_column='id',
)

[INFO ] PyDI.entitymatching.rule_based.RuleBasedMatcher - Starting Entity Matching
[INFO ] PyDI.entitymatching.rule_based.RuleBasedMatcher - Blocking 84445 x 14666 elements
[INFO ] PyDI.entitymatching.rule_based.RuleBasedMatcher - Matching 84445 x 14666 elements after 0:00:0.044; 453398 blocked pairs (reduction ratio: 0.9996339048466698)
[INFO ] PyDI.entitymatching.rule_based.RuleBasedMatcher - Entity Matching finished after 0:00:42.443; found 9127 correspondences.
[INFO ] PyDI.entitymatching.rule_based.RuleBasedMatcher - Starting Entity Matching
[INFO ] PyDI.entitymatching.rule_based.RuleBasedMatcher - Blocking 84445 x 16325 elements
[INFO ] PyDI.entitymatching.rule_based.RuleBasedMatcher - Matching 84445 x 16325 elements after 0:00:0.014; 378750 blocked pairs (reduction ratio: 0.9997252577114403)
[INFO ] PyDI.entitymatching.rule_based.RuleBasedMatcher - Entity Matching finished after 0:00:32.844; found 6648 correspondences.

In [102]:
print(len(correspondences_p2m))
print(len(correspondences_p2s))

9127
6648

In [103]:
cluster_analysis_dir = OUTPUT_DIR / "cluster_analysis"
cluster_analysis_dir.mkdir(parents=True, exist_ok=True)
cluster_distribution_p2m_rb_2 = EntityMatchingEvaluator.create_cluster_size_distribution(
    correspondences=correspondences_p2m,
    out_dir=cluster_analysis_dir
)
cluster_distribution_p2s_rb_2 = EntityMatchingEvaluator.create_cluster_size_distribution(
    correspondences=correspondences_p2s,
    out_dir=cluster_analysis_dir
)

[INFO ] PyDI.entitymatching.evaluation - Cluster Size Distribution of 8762 clusters:
[INFO ] PyDI.entitymatching.evaluation - 	Cluster Size	| Frequency	| Percentage
[INFO ] PyDI.entitymatching.evaluation - 	──────────────────────────────────────────────────
[INFO ] PyDI.entitymatching.evaluation - 		2	|	8527	|	97.32%
[INFO ] PyDI.entitymatching.evaluation - 		3	|	169	|	1.93%
[INFO ] PyDI.entitymatching.evaluation - 		4	|	43	|	0.49%
[INFO ] PyDI.entitymatching.evaluation - 		5	|	20	|	0.23%
[INFO ] PyDI.entitymatching.evaluation - 		6	|	1	|	0.01%
[INFO ] PyDI.entitymatching.evaluation - 		7	|	2	|	0.02%
[INFO ] root - Cluster size distribution written to /Users/onurcanmemis/Desktop/web-data-integration-team-project/output/cluster_analysis/cluster_size_distribution.csv
[INFO ] PyDI.entitymatching.evaluation - Cluster Size Distribution of 6258 clusters:
[INFO ] PyDI.entitymatching.evaluation - 	Cluster Size	| Frequency	| Percentage
[INFO ] PyDI.entitymatching.evaluation - 	──────────────────────────────────────────────────
[INFO ] PyDI.entitymatching.evaluation - 		2	|	6020	|	96.20%
[INFO ] PyDI.entitymatching.evaluation - 		3	|	174	|	2.78%
[INFO ] PyDI.entitymatching.evaluation - 		4	|	46	|	0.74%
[INFO ] PyDI.entitymatching.evaluation - 		5	|	13	|	0.21%
[INFO ] PyDI.entitymatching.evaluation - 		6	|	2	|	0.03%
[INFO ] PyDI.entitymatching.evaluation - 		7	|	1	|	0.02%
[INFO ] PyDI.entitymatching.evaluation - 		8	|	2	|	0.03%
[INFO ] root - Cluster size distribution written to /Users/onurcanmemis/Desktop/web-data-integration-team-project/output/cluster_analysis/cluster_size_distribution.csv

In [104]:
print(f"\n📊 Cluster Size Distribution Results (Playtime -> Metacritic):")
display(cluster_distribution_p2m_rb_2)
print(f"\n📊 Cluster Size Distribution Results (Playtime -> VGSales):")
display(cluster_distribution_p2s_rb_2)

📊 Cluster Size Distribution Results (Playtime -> Metacritic):

   cluster_size  frequency  percentage
0             2       8527   97.317964
1             3        169    1.928783
2             4         43    0.490756
3             5         20    0.228258
4             6          1    0.011413
5             7          2    0.022826

📊 Cluster Size Distribution Results (Playtime -> VGSales):

   cluster_size  frequency  percentage
0             2       6020   96.196868
1             3        174    2.780441
2             4         46    0.735059
3             5         13    0.207734
4             6          2    0.031959
5             7          1    0.015980
6             8          2    0.031959

### RB Matching Evaluation
#### Playtime -> Metacritic

In [105]:
debug_output_dir = OUTPUT_DIR / "debug_results_entity_matching"
debug_output_dir.mkdir(parents=True, exist_ok=True)

eval_results_p2m = EntityMatchingEvaluator.evaluate_matching(
    correspondences=correspondences_p2m,
    test_pairs=test_p2m,
    out_dir=debug_output_dir
)

display(eval_results_p2m)

[INFO ] root - Confusion Matrix:
[INFO ] root -   True Positives:  91
[INFO ] root -   True Negatives:  53
[INFO ] root -   False Positives: 2
[INFO ] root -   False Negatives: 2
[INFO ] root - Performance Metrics:
[INFO ] root -   Accuracy:  0.973
[INFO ] root -   Precision: 0.978
[INFO ] root -   Recall:    0.978
[INFO ] root -   F1-Score:  0.978

{'precision': 0.978494623655914,
 'recall': 0.978494623655914,
 'f1': 0.978494623655914,
 'accuracy': 0.972972972972973,
 'true_positives': 91,
 'false_positives': 2,
 'false_negatives': 2,
 'true_negatives': 53,
 'threshold_used': 0.0,
 'total_correspondences': 9127,
 'filtered_correspondences': 9127,
 'evaluation_timestamp': '2025-11-29T15:55:13.603175',
 'output_files': ['/Users/onurcanmemis/Desktop/web-data-integration-team-project/output/debug_results_entity_matching/matching_evaluation_summary.json',
  '/Users/onurcanmemis/Desktop/web-data-integration-team-project/output/debug_results_entity_matching/matching_detailed_results.csv']}

#### Playtime -> Sales

In [106]:
eval_results_p2s = EntityMatchingEvaluator.evaluate_matching(
    correspondences=correspondences_p2s,
    test_pairs=test_p2s,
    out_dir=debug_output_dir
)

display(eval_results_p2s)

[INFO ] root - Confusion Matrix:
[INFO ] root -   True Positives:  78
[INFO ] root -   True Negatives:  54
[INFO ] root -   False Positives: 0
[INFO ] root -   False Negatives: 17
[INFO ] root - Performance Metrics:
[INFO ] root -   Accuracy:  0.886
[INFO ] root -   Precision: 1.000
[INFO ] root -   Recall:    0.821
[INFO ] root -   F1-Score:  0.902

{'precision': 1.0,
 'recall': 0.8210526315789474,
 'f1': 0.9017341040462429,
 'accuracy': 0.8859060402684564,
 'true_positives': 78,
 'false_positives': 0,
 'false_negatives': 17,
 'true_negatives': 54,
 'threshold_used': 0.0,
 'total_correspondences': 6648,
 'filtered_correspondences': 6648,
 'evaluation_timestamp': '2025-11-29T15:55:16.860241',
 'output_files': ['/Users/onurcanmemis/Desktop/web-data-integration-team-project/output/debug_results_entity_matching/matching_evaluation_summary.json',
  '/Users/onurcanmemis/Desktop/web-data-integration-team-project/output/debug_results_entity_matching/matching_detailed_results.csv']}

In [107]:
from PyDI.entitymatching import MaximumBipartiteMatching, StableMatching

# We are using Maxmimum Bipartite Matching to refine results to 1:1 matches
clusterer = MaximumBipartiteMatching()
mbm_correspondences_p2m = clusterer.cluster(correspondences_p2m)
mbm_correspondences_p2s = clusterer.cluster(correspondences_p2s)

[INFO ] root - Filtered correspondences: 9127 -> 9127 (threshold=0.0)
[INFO ] root - Maximum bipartite matching: 9127 -> 8805
[INFO ] root - MaximumBipartiteMatching: 9127 -> 8805 correspondences
[INFO ] root - MaximumBipartiteMatching: 17853 -> 17610 entities
[INFO ] root - Filtered correspondences: 6648 -> 6648 (threshold=0.0)
[INFO ] root - Maximum bipartite matching: 6648 -> 6320
[INFO ] root - MaximumBipartiteMatching: 6648 -> 6320 correspondences
[INFO ] root - MaximumBipartiteMatching: 12846 -> 12640 entities

In [108]:
eval_p2m = EntityMatchingEvaluator.evaluate_matching(
                correspondences=mbm_correspondences_p2m,
                test_pairs=test_p2m,
                out_dir=BLOCK_EVAL_DIR,
            )

display(eval_p2m)

[INFO ] root - Confusion Matrix:
[INFO ] root -   True Positives:  90
[INFO ] root -   True Negatives:  54
[INFO ] root -   False Positives: 1
[INFO ] root -   False Negatives: 3
[INFO ] root - Performance Metrics:
[INFO ] root -   Accuracy:  0.973
[INFO ] root -   Precision: 0.989
[INFO ] root -   Recall:    0.968
[INFO ] root -   F1-Score:  0.978

{'precision': 0.989010989010989,
 'recall': 0.967741935483871,
 'f1': 0.9782608695652174,
 'accuracy': 0.972972972972973,
 'true_positives': 90,
 'false_positives': 1,
 'false_negatives': 3,
 'true_negatives': 54,
 'threshold_used': 0.0,
 'total_correspondences': 8805,
 'filtered_correspondences': 8805,
 'evaluation_timestamp': '2025-11-29T15:58:14.292072',
 'output_files': ['/Users/onurcanmemis/Desktop/web-data-integration-team-project/output/blocking_evaluation/matching_evaluation_summary.json',
  '/Users/onurcanmemis/Desktop/web-data-integration-team-project/output/blocking_evaluation/matching_detailed_results.csv']}

In [109]:
eval_p2s = EntityMatchingEvaluator.evaluate_matching(
                correspondences=mbm_correspondences_p2s,
                test_pairs=test_p2s,
                out_dir=BLOCK_EVAL_DIR,
            )

display(eval_p2s)

[INFO ] root - Confusion Matrix:
[INFO ] root -   True Positives:  75
[INFO ] root -   True Negatives:  54
[INFO ] root -   False Positives: 0
[INFO ] root -   False Negatives: 20
[INFO ] root - Performance Metrics:
[INFO ] root -   Accuracy:  0.866
[INFO ] root -   Precision: 1.000
[INFO ] root -   Recall:    0.789
[INFO ] root -   F1-Score:  0.882

{'precision': 1.0,
 'recall': 0.7894736842105263,
 'f1': 0.8823529411764706,
 'accuracy': 0.8657718120805369,
 'true_positives': 75,
 'false_positives': 0,
 'false_negatives': 20,
 'true_negatives': 54,
 'threshold_used': 0.0,
 'total_correspondences': 6320,
 'filtered_correspondences': 6320,
 'evaluation_timestamp': '2025-11-29T15:58:18.225323',
 'output_files': ['/Users/onurcanmemis/Desktop/web-data-integration-team-project/output/blocking_evaluation/matching_evaluation_summary.json',
  '/Users/onurcanmemis/Desktop/web-data-integration-team-project/output/blocking_evaluation/matching_detailed_results.csv']}

## ML Based Matcher

In [57]:
from PyDI.entitymatching import FeatureExtractor

comparators_ml_base = [
    StringComparator(column='title_norm', similarity_function='cosine'),

    StringComparator(column='platform', similarity_function='identity'),

    NumericComparator(column="release_year",method="within_range",max_difference=0),   # exact match only


]

comparators_ml_p2m = comparators_ml_base + [
    StringComparator(column='developer', similarity_function='cosine',preprocess=str.lower),
]

comparators_ml_p2s = comparators_ml_base + [
    StringComparator(column='publisher', similarity_function='cosine',preprocess=str.lower),
]

feature_extractor_p2m = FeatureExtractor(comparators_ml_p2m)
feature_extractor_p2s = FeatureExtractor(comparators_ml_p2s)

train_features_p2m = feature_extractor_p2m.create_features(
    playtime, metacritic, train_p2m[['id1', 'id2']], labels=train_p2m['label'], id_column='id'
)

train_features_p2s = feature_extractor_p2s.create_features(
    playtime, vgsales, train_p2s[['id1', 'id2']], labels=train_p2s['label'], id_column='id'
)

feature_columns_p2m = [col for col in train_features_p2m.columns if col not in ['id1', 'id2', 'label']]
X_train_p2m = train_features_p2m[feature_columns_p2m]
y_train_p2m = train_features_p2m['label']

feature_columns_p2s = [col for col in train_features_p2s.columns if col not in ['id1', 'id2', 'label']]
X_train_p2s = train_features_p2s[feature_columns_p2s]
y_train_p2s = train_features_p2s['label']

training_datasets = [(X_train_p2m, y_train_p2m),(X_train_p2s, y_train_p2s)]

[INFO ] root - Label distribution: 374 positive, 220 negative
[INFO ] root - Label distribution: 379 positive, 218 negative

In [58]:
from sklearn.model_selection import GridSearchCV, StratifiedKFold
from sklearn.ensemble import RandomForestClassifier, GradientBoostingClassifier
from sklearn.svm import SVC
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import make_scorer, f1_score
import os
os.environ["TOKENIZERS_PARALLELISM"] = "false"
# classifiers
classifiers = {
    'RandomForestClassifier': RandomForestClassifier(random_state=42),
    'GradientBoostingClassifier': GradientBoostingClassifier(random_state=42),
    'SVC': SVC(probability=True, random_state=42),
    'LogisticRegression': LogisticRegression(max_iter=1000, random_state=42)
}

# parameter grids
param_grids = {
    'RandomForestClassifier': {
        'n_estimators': [50, 100, 200, 500],
        'max_depth': [None, 10, 20],
        'class_weight': ['balanced', None],
        'min_samples_split': [2, 5]
    },
    'GradientBoostingClassifier': {
        'n_estimators': [100, 200],
        'learning_rate': [0.05, 0.1],
        'max_depth': [3, 5]
    },
    'SVC': {
        'C': [0.1, 1, 10],
        'kernel': ['linear', 'rbf'],
        'gamma': ['scale', 'auto']
    },
    'LogisticRegression': {
        'C': [0.01, 0.1, 1, 10],
        'penalty': ['l2'],
        'solver': ['lbfgs', 'liblinear']
    }
}

scorer = make_scorer(f1_score)
cv_folds = StratifiedKFold(n_splits=5, shuffle=True, random_state=42)


best_models = []  # one best model per dataset

for (X_train, y_train) in training_datasets:
    grid_search_results = {}
    best_overall_score = -1
    best_overall_model = None
    best_model_name = None

    for name, model in classifiers.items():
        print(f"Running GridSearchCV for {name}...")
        
        grid = GridSearchCV(
            estimator=model,
            param_grid=param_grids[name],
            scoring=scorer,
            cv=cv_folds,
            n_jobs=-1,
            verbose=0
        )
        
        grid.fit(X_train, y_train)
        print(
            f"{name}: best F1 = {grid.best_score_:.4f} "
            f"with params {grid.best_params_}"
        )
        
        grid_search_results[name] = {
            'grid_search': grid,
            'best_score': grid.best_score_,
            'best_params': grid.best_params_,
            'best_estimator': grid.best_estimator_
        }

        if grid.best_score_ > best_overall_score:
            best_overall_score = grid.best_score_   
            best_overall_model = grid.best_estimator_
            best_model_name = name

    print(f"Best model for this dataset: {best_model_name} with F1={best_overall_score:.4f}")
    best_models.append(best_overall_model)

Running GridSearchCV for RandomForestClassifier...
RandomForestClassifier: best F1 = 0.9880 with params {'class_weight': 'balanced', 'max_depth': None, 'min_samples_split': 2, 'n_estimators': 200}
Running GridSearchCV for GradientBoostingClassifier...
GradientBoostingClassifier: best F1 = 0.9880 with params {'learning_rate': 0.05, 'max_depth': 3, 'n_estimators': 100}
Running GridSearchCV for SVC...
SVC: best F1 = 0.9855 with params {'C': 1, 'gamma': 'scale', 'kernel': 'rbf'}
Running GridSearchCV for LogisticRegression...
LogisticRegression: best F1 = 0.9842 with params {'C': 10, 'penalty': 'l2', 'solver': 'lbfgs'}
Best model for this dataset: RandomForestClassifier with F1=0.9880
Running GridSearchCV for RandomForestClassifier...
RandomForestClassifier: best F1 = 0.9817 with params {'class_weight': 'balanced', 'max_depth': None, 'min_samples_split': 2, 'n_estimators': 100}
Running GridSearchCV for GradientBoostingClassifier...
GradientBoostingClassifier: best F1 = 0.9764 with params {'learning_rate': 0.1, 'max_depth': 5, 'n_estimators': 200}
Running GridSearchCV for SVC...
SVC: best F1 = 0.9768 with params {'C': 10, 'gamma': 'scale', 'kernel': 'rbf'}
Running GridSearchCV for LogisticRegression...
LogisticRegression: best F1 = 0.9756 with params {'C': 0.1, 'penalty': 'l2', 'solver': 'lbfgs'}
Best model for this dataset: RandomForestClassifier with F1=0.9817

In [59]:
display(best_models)

[RandomForestClassifier(class_weight='balanced', n_estimators=200,
                        random_state=42),
 RandomForestClassifier(class_weight='balanced', random_state=42)]

In [71]:
from PyDI.entitymatching import MLBasedMatcher

ml_matcher_p2m= MLBasedMatcher(feature_extractor_p2m)
ml_matcher_p2s= MLBasedMatcher(feature_extractor_p2s)


correspondences_p2m= ml_matcher_p2m.match(
    playtime, metacritic,
    candidates=embedding_candidates_p2m,
    id_column='id',
    trained_classifier=best_models[0],
    use_probabilities=True,
    threshold=0.8
)

correspondences_p2s = ml_matcher_p2s.match(
    playtime, vgsales,
    candidates=embedding_candidates_p2s,
    id_column='id',
    trained_classifier=best_models[1],
    use_probabilities=True,
    threshold=0.8
)

[INFO ] PyDI.entitymatching.ml_based.MLBasedMatcher - Starting Entity Matching
[INFO ] PyDI.entitymatching.ml_based.MLBasedMatcher - Blocking 84445 x 14666 elements
[INFO ] PyDI.entitymatching.ml_based.MLBasedMatcher - Matching 84445 x 14666 elements after 0:00:0.001; 453398 blocked pairs (reduction ratio: 0.9996339048466698)
[INFO ] PyDI.entitymatching.ml_based.MLBasedMatcher - Entity Matching finished after 0:00:46.061; found 9240 correspondences.
[INFO ] PyDI.entitymatching.ml_based.MLBasedMatcher - Starting Entity Matching
[INFO ] PyDI.entitymatching.ml_based.MLBasedMatcher - Blocking 84445 x 16325 elements
[INFO ] PyDI.entitymatching.ml_based.MLBasedMatcher - Matching 84445 x 16325 elements after 0:00:0.000; 378750 blocked pairs (reduction ratio: 0.9997252577114403)
[INFO ] PyDI.entitymatching.ml_based.MLBasedMatcher - Entity Matching finished after 0:00:35.847; found 7140 correspondences.

In [61]:
print(len(correspondences_p2m))
print(len(correspondences_p2s))

9240
7140

In [72]:
cluster_analysis_dir = OUTPUT_DIR / "cluster_analysis"
cluster_analysis_dir.mkdir(parents=True, exist_ok=True)
cluster_distribution_p2m_ml_1 = EntityMatchingEvaluator.create_cluster_size_distribution(
    correspondences=correspondences_p2m,
    out_dir=cluster_analysis_dir
)
cluster_distribution_p2s_ml_1 = EntityMatchingEvaluator.create_cluster_size_distribution(
    correspondences=correspondences_p2s,
    out_dir=cluster_analysis_dir
)

[INFO ] PyDI.entitymatching.evaluation - Cluster Size Distribution of 8788 clusters:
[INFO ] PyDI.entitymatching.evaluation - 	Cluster Size	| Frequency	| Percentage
[INFO ] PyDI.entitymatching.evaluation - 	──────────────────────────────────────────────────
[INFO ] PyDI.entitymatching.evaluation - 		2	|	8501	|	96.73%
[INFO ] PyDI.entitymatching.evaluation - 		3	|	205	|	2.33%
[INFO ] PyDI.entitymatching.evaluation - 		4	|	55	|	0.63%
[INFO ] PyDI.entitymatching.evaluation - 		5	|	21	|	0.24%
[INFO ] PyDI.entitymatching.evaluation - 		6	|	4	|	0.05%
[INFO ] PyDI.entitymatching.evaluation - 		7	|	2	|	0.02%
[INFO ] root - Cluster size distribution written to /Users/onurcanmemis/Desktop/web-data-integration-team-project/output/cluster_analysis/cluster_size_distribution.csv
[INFO ] PyDI.entitymatching.evaluation - Cluster Size Distribution of 6295 clusters:
[INFO ] PyDI.entitymatching.evaluation - 	Cluster Size	| Frequency	| Percentage
[INFO ] PyDI.entitymatching.evaluation - 	──────────────────────────────────────────────────
[INFO ] PyDI.entitymatching.evaluation - 		2	|	5805	|	92.22%
[INFO ] PyDI.entitymatching.evaluation - 		3	|	334	|	5.31%
[INFO ] PyDI.entitymatching.evaluation - 		4	|	106	|	1.68%
[INFO ] PyDI.entitymatching.evaluation - 		5	|	25	|	0.40%
[INFO ] PyDI.entitymatching.evaluation - 		6	|	12	|	0.19%
[INFO ] PyDI.entitymatching.evaluation - 		7	|	8	|	0.13%
[INFO ] PyDI.entitymatching.evaluation - 		8	|	3	|	0.05%
[INFO ] PyDI.entitymatching.evaluation - 		9	|	2	|	0.03%
[INFO ] root - Cluster size distribution written to /Users/onurcanmemis/Desktop/web-data-integration-team-project/output/cluster_analysis/cluster_size_distribution.csv

### ML Matching Evaluation
#### Playtime -> Metacritic

In [39]:
eval_p2m = EntityMatchingEvaluator.evaluate_matching(
                correspondences=correspondences_p2m,
                test_pairs=test_p2m,
                out_dir=BLOCK_EVAL_DIR,
            )

display(eval_p2m)

[INFO ] root - Confusion Matrix:
[INFO ] root -   True Positives:  92
[INFO ] root -   True Negatives:  52
[INFO ] root -   False Positives: 3
[INFO ] root -   False Negatives: 1
[INFO ] root - Performance Metrics:
[INFO ] root -   Accuracy:  0.973
[INFO ] root -   Precision: 0.968
[INFO ] root -   Recall:    0.989
[INFO ] root -   F1-Score:  0.979

{'precision': 0.968421052631579,
 'recall': 0.989247311827957,
 'f1': 0.9787234042553192,
 'accuracy': 0.972972972972973,
 'true_positives': 92,
 'false_positives': 3,
 'false_negatives': 1,
 'true_negatives': 52,
 'threshold_used': 0.0,
 'total_correspondences': 9240,
 'filtered_correspondences': 9240,
 'evaluation_timestamp': '2025-11-29T13:58:03.565095',
 'output_files': ['/Users/onurcanmemis/Desktop/web-data-integration-team-project/output/blocking_evaluation/matching_evaluation_summary.json',
  '/Users/onurcanmemis/Desktop/web-data-integration-team-project/output/blocking_evaluation/matching_detailed_results.csv']}

#### Playtime -> Sales

In [40]:
eval_p2s = EntityMatchingEvaluator.evaluate_matching(
                correspondences=correspondences_p2s,
                test_pairs=test_p2s,
                out_dir=BLOCK_EVAL_DIR,
            )

display(eval_p2s)

[INFO ] root - Confusion Matrix:
[INFO ] root -   True Positives:  84
[INFO ] root -   True Negatives:  53
[INFO ] root -   False Positives: 1
[INFO ] root -   False Negatives: 11
[INFO ] root - Performance Metrics:
[INFO ] root -   Accuracy:  0.919
[INFO ] root -   Precision: 0.988
[INFO ] root -   Recall:    0.884
[INFO ] root -   F1-Score:  0.933

{'precision': 0.9882352941176471,
 'recall': 0.8842105263157894,
 'f1': 0.9333333333333333,
 'accuracy': 0.9194630872483222,
 'true_positives': 84,
 'false_positives': 1,
 'false_negatives': 11,
 'true_negatives': 53,
 'threshold_used': 0.0,
 'total_correspondences': 7140,
 'filtered_correspondences': 7140,
 'evaluation_timestamp': '2025-11-29T13:58:03.962755',
 'output_files': ['/Users/onurcanmemis/Desktop/web-data-integration-team-project/output/blocking_evaluation/matching_evaluation_summary.json',
  '/Users/onurcanmemis/Desktop/web-data-integration-team-project/output/blocking_evaluation/matching_detailed_results.csv']}

In [41]:
from PyDI.entitymatching import MaximumBipartiteMatching, StableMatching

# We are using Maxmimum Bipartite Matching to refine results to 1:1 matches
clusterer = MaximumBipartiteMatching()
mbm_correspondences_p2m = clusterer.cluster(correspondences_p2m)
mbm_correspondences_p2s = clusterer.cluster(correspondences_p2s)

[INFO ] root - Filtered correspondences: 9240 -> 9240 (threshold=0.0)
[INFO ] root - Maximum bipartite matching: 9240 -> 8845
[INFO ] root - MaximumBipartiteMatching: 9240 -> 8845 correspondences
[INFO ] root - MaximumBipartiteMatching: 17980 -> 17690 entities
[INFO ] root - Filtered correspondences: 7140 -> 7140 (threshold=0.0)
[INFO ] root - Maximum bipartite matching: 7140 -> 6449
[INFO ] root - MaximumBipartiteMatching: 7140 -> 6449 correspondences
[INFO ] root - MaximumBipartiteMatching: 13331 -> 12898 entities

In [42]:
eval_p2m = EntityMatchingEvaluator.evaluate_matching(
                correspondences=mbm_correspondences_p2m,
                test_pairs=test_p2m,
                out_dir=BLOCK_EVAL_DIR,
            )

display(eval_p2m)

[INFO ] root - Confusion Matrix:
[INFO ] root -   True Positives:  90
[INFO ] root -   True Negatives:  54
[INFO ] root -   False Positives: 1
[INFO ] root -   False Negatives: 3
[INFO ] root - Performance Metrics:
[INFO ] root -   Accuracy:  0.973
[INFO ] root -   Precision: 0.989
[INFO ] root -   Recall:    0.968
[INFO ] root -   F1-Score:  0.978

{'precision': 0.989010989010989,
 'recall': 0.967741935483871,
 'f1': 0.9782608695652174,
 'accuracy': 0.972972972972973,
 'true_positives': 90,
 'false_positives': 1,
 'false_negatives': 3,
 'true_negatives': 54,
 'threshold_used': 0.0,
 'total_correspondences': 8845,
 'filtered_correspondences': 8845,
 'evaluation_timestamp': '2025-11-29T13:58:04.971792',
 'output_files': ['/Users/onurcanmemis/Desktop/web-data-integration-team-project/output/blocking_evaluation/matching_evaluation_summary.json',
  '/Users/onurcanmemis/Desktop/web-data-integration-team-project/output/blocking_evaluation/matching_detailed_results.csv']}

In [43]:
eval_p2s = EntityMatchingEvaluator.evaluate_matching(
                correspondences=mbm_correspondences_p2s,
                test_pairs=test_p2s,
                out_dir=BLOCK_EVAL_DIR,
            )

display(eval_p2s)

[INFO ] root - Confusion Matrix:
[INFO ] root -   True Positives:  79
[INFO ] root -   True Negatives:  53
[INFO ] root -   False Positives: 1
[INFO ] root -   False Negatives: 16
[INFO ] root - Performance Metrics:
[INFO ] root -   Accuracy:  0.886
[INFO ] root -   Precision: 0.988
[INFO ] root -   Recall:    0.832
[INFO ] root -   F1-Score:  0.903

{'precision': 0.9875,
 'recall': 0.8315789473684211,
 'f1': 0.9028571428571428,
 'accuracy': 0.8859060402684564,
 'true_positives': 79,
 'false_positives': 1,
 'false_negatives': 16,
 'true_negatives': 53,
 'threshold_used': 0.0,
 'total_correspondences': 6449,
 'filtered_correspondences': 6449,
 'evaluation_timestamp': '2025-11-29T13:58:05.284702',
 'output_files': ['/Users/onurcanmemis/Desktop/web-data-integration-team-project/output/blocking_evaluation/matching_evaluation_summary.json',
  '/Users/onurcanmemis/Desktop/web-data-integration-team-project/output/blocking_evaluation/matching_detailed_results.csv']}

## ML Based Matcher_2 (Without Threshold)

In [73]:
from PyDI.entitymatching import MLBasedMatcher

ml_matcher_p2m= MLBasedMatcher(feature_extractor_p2m)
ml_matcher_p2s= MLBasedMatcher(feature_extractor_p2s)


correspondences_p2m= ml_matcher_p2m.match(
    playtime, metacritic,
    candidates=embedding_candidates_p2m,
    id_column='id',
    trained_classifier=best_models[0],
)

correspondences_p2s = ml_matcher_p2s.match(
    playtime, vgsales,
    candidates=embedding_candidates_p2s,
    id_column='id',
    trained_classifier=best_models[1],
)

[INFO ] PyDI.entitymatching.ml_based.MLBasedMatcher - Starting Entity Matching
[INFO ] PyDI.entitymatching.ml_based.MLBasedMatcher - Blocking 84445 x 14666 elements
[INFO ] PyDI.entitymatching.ml_based.MLBasedMatcher - Matching 84445 x 14666 elements after 0:00:0.004; 453398 blocked pairs (reduction ratio: 0.9996339048466698)
[INFO ] PyDI.entitymatching.ml_based.MLBasedMatcher - Entity Matching finished after 0:00:44.390; found 61166 correspondences.
[INFO ] PyDI.entitymatching.ml_based.MLBasedMatcher - Starting Entity Matching
[INFO ] PyDI.entitymatching.ml_based.MLBasedMatcher - Blocking 84445 x 16325 elements
[INFO ] PyDI.entitymatching.ml_based.MLBasedMatcher - Matching 84445 x 16325 elements after 0:00:0.000; 378750 blocked pairs (reduction ratio: 0.9997252577114403)
[INFO ] PyDI.entitymatching.ml_based.MLBasedMatcher - Entity Matching finished after 0:00:35.747; found 54402 correspondences.

In [63]:
print(len(correspondences_p2m))
print(len(correspondences_p2s))

61166
54402

In [74]:
cluster_analysis_dir = OUTPUT_DIR / "cluster_analysis"
cluster_analysis_dir.mkdir(parents=True, exist_ok=True)
cluster_distribution_p2m_ml_2 = EntityMatchingEvaluator.create_cluster_size_distribution(
    correspondences=correspondences_p2m,
    out_dir=cluster_analysis_dir
)
cluster_distribution_p2s_ml_2 = EntityMatchingEvaluator.create_cluster_size_distribution(
    correspondences=correspondences_p2s,
    out_dir=cluster_analysis_dir
)

[INFO ] PyDI.entitymatching.evaluation - Cluster Size Distribution of 6093 clusters:
[INFO ] PyDI.entitymatching.evaluation - 	Cluster Size	| Frequency	| Percentage
[INFO ] PyDI.entitymatching.evaluation - 	──────────────────────────────────────────────────
[INFO ] PyDI.entitymatching.evaluation - 		2	|	1703	|	27.95%
[INFO ] PyDI.entitymatching.evaluation - 		3	|	841	|	13.80%
[INFO ] PyDI.entitymatching.evaluation - 		4	|	785	|	12.88%
[INFO ] PyDI.entitymatching.evaluation - 		5	|	588	|	9.65%
[INFO ] PyDI.entitymatching.evaluation - 		6	|	575	|	9.44%
[INFO ] PyDI.entitymatching.evaluation - 		7	|	348	|	5.71%
[INFO ] PyDI.entitymatching.evaluation - 		8	|	313	|	5.14%
[INFO ] PyDI.entitymatching.evaluation - 		9	|	207	|	3.40%
[INFO ] PyDI.entitymatching.evaluation - 		10	|	128	|	2.10%
[INFO ] PyDI.entitymatching.evaluation - 		11	|	112	|	1.84%
[INFO ] PyDI.entitymatching.evaluation - 		12	|	66	|	1.08%
[INFO ] PyDI.entitymatching.evaluation - 		13	|	59	|	0.97%
[INFO ] PyDI.entitymatching.evaluation - 		14	|	52	|	0.85%
[INFO ] PyDI.entitymatching.evaluation - 		15	|	24	|	0.39%
[INFO ] PyDI.entitymatching.evaluation - 		16	|	31	|	0.51%
[INFO ] PyDI.entitymatching.evaluation - 		17	|	26	|	0.43%
[INFO ] PyDI.entitymatching.evaluation - 		18	|	19	|	0.31%
[INFO ] PyDI.entitymatching.evaluation - 		19	|	19	|	0.31%
[INFO ] PyDI.entitymatching.evaluation - 		20	|	11	|	0.18%
[INFO ] PyDI.entitymatching.evaluation - 		21	|	19	|	0.31%
[INFO ] PyDI.entitymatching.evaluation - 		22	|	11	|	0.18%
[INFO ] PyDI.entitymatching.evaluation - 		23	|	12	|	0.20%
[INFO ] PyDI.entitymatching.evaluation - 		24	|	6	|	0.10%
[INFO ] PyDI.entitymatching.evaluation - 		25	|	6	|	0.10%
[INFO ] PyDI.entitymatching.evaluation - 		26	|	11	|	0.18%
[INFO ] PyDI.entitymatching.evaluation - 		27	|	10	|	0.16%
[INFO ] PyDI.entitymatching.evaluation - 		28	|	12	|	0.20%
[INFO ] PyDI.entitymatching.evaluation - 		29	|	7	|	0.11%
[INFO ] PyDI.entitymatching.evaluation - 		30	|	3	|	0.05%
[INFO ] PyDI.entitymatching.evaluation - 		31	|	3	|	0.05%
[INFO ] PyDI.entitymatching.evaluation - 		32	|	2	|	0.03%
[INFO ] PyDI.entitymatching.evaluation - 		33	|	4	|	0.07%
[INFO ] PyDI.entitymatching.evaluation - 		34	|	2	|	0.03%
[INFO ] PyDI.entitymatching.evaluation - 		35	|	3	|	0.05%
[INFO ] PyDI.entitymatching.evaluation - 		36	|	2	|	0.03%
[INFO ] PyDI.entitymatching.evaluation - 		37	|	4	|	0.07%
[INFO ] PyDI.entitymatching.evaluation - 		38	|	1	|	0.02%
[INFO ] PyDI.entitymatching.evaluation - 		39	|	4	|	0.07%
[INFO ] PyDI.entitymatching.evaluation - 		40	|	2	|	0.03%
[INFO ] PyDI.entitymatching.evaluation - 		41	|	1	|	0.02%
[INFO ] PyDI.entitymatching.evaluation - 		42	|	3	|	0.05%
[INFO ] PyDI.entitymatching.evaluation - 		43	|	3	|	0.05%
[INFO ] PyDI.entitymatching.evaluation - 		44	|	3	|	0.05%
[INFO ] PyDI.entitymatching.evaluation - 		45	|	2	|	0.03%
[INFO ] PyDI.entitymatching.evaluation - 		46	|	2	|	0.03%
[INFO ] PyDI.entitymatching.evaluation - 		47	|	1	|	0.02%
[INFO ] PyDI.entitymatching.evaluation - 		48	|	1	|	0.02%
[INFO ] PyDI.entitymatching.evaluation - 		50	|	1	|	0.02%
[INFO ] PyDI.entitymatching.evaluation - 		53	|	3	|	0.05%
[INFO ] PyDI.entitymatching.evaluation - 		55	|	1	|	0.02%
[INFO ] PyDI.entitymatching.evaluation - 		56	|	4	|	0.07%
[INFO ] PyDI.entitymatching.evaluation - 		57	|	3	|	0.05%
[INFO ] PyDI.entitymatching.evaluation - 		58	|	2	|	0.03%
[INFO ] PyDI.entitymatching.evaluation - 		59	|	1	|	0.02%
[INFO ] PyDI.entitymatching.evaluation - 		62	|	4	|	0.07%
[INFO ] PyDI.entitymatching.evaluation - 		65	|	1	|	0.02%
[INFO ] PyDI.entitymatching.evaluation - 		66	|	1	|	0.02%
[INFO ] PyDI.entitymatching.evaluation - 		70	|	2	|	0.03%
[INFO ] PyDI.entitymatching.evaluation - 		71	|	2	|	0.03%
[INFO ] PyDI.entitymatching.evaluation - 		73	|	1	|	0.02%
[INFO ] PyDI.entitymatching.evaluation - 		74	|	1	|	0.02%
[INFO ] PyDI.entitymatching.evaluation - 		80	|	2	|	0.03%
[INFO ] PyDI.entitymatching.evaluation - 		81	|	1	|	0.02%
[INFO ] PyDI.entitymatching.evaluation - 		82	|	1	|	0.02%
[INFO ] PyDI.entitymatching.evaluation - 		89	|	1	|	0.02%
[INFO ] PyDI.entitymatching.evaluation - 		101	|	1	|	0.02%
[INFO ] PyDI.entitymatching.evaluation - 		105	|	1	|	0.02%
[INFO ] PyDI.entitymatching.evaluation - 		107	|	1	|	0.02%
[INFO ] PyDI.entitymatching.evaluation - 		117	|	1	|	0.02%
[INFO ] PyDI.entitymatching.evaluation - 		121	|	1	|	0.02%
[INFO ] PyDI.entitymatching.evaluation - 		124	|	1	|	0.02%
[INFO ] PyDI.entitymatching.evaluation - 		125	|	1	|	0.02%
[INFO ] PyDI.entitymatching.evaluation - 		134	|	1	|	0.02%
[INFO ] PyDI.entitymatching.evaluation - 		139	|	1	|	0.02%
[INFO ] PyDI.entitymatching.evaluation - 		154	|	1	|	0.02%
[INFO ] PyDI.entitymatching.evaluation - 		188	|	1	|	0.02%
[INFO ] PyDI.entitymatching.evaluation - 		189	|	1	|	0.02%
[INFO ] PyDI.entitymatching.evaluation - 		202	|	1	|	0.02%
[INFO ] PyDI.entitymatching.evaluation - 		203	|	1	|	0.02%
[INFO ] root - Cluster size distribution written to /Users/onurcanmemis/Desktop/web-data-integration-team-project/output/cluster_analysis/cluster_size_distribution.csv
[INFO ] PyDI.entitymatching.evaluation - Cluster Size Distribution of 3844 clusters:
[INFO ] PyDI.entitymatching.evaluation - 	Cluster Size	| Frequency	| Percentage
[INFO ] PyDI.entitymatching.evaluation - 	──────────────────────────────────────────────────
[INFO ] PyDI.entitymatching.evaluation - 		2	|	2014	|	52.39%
[INFO ] PyDI.entitymatching.evaluation - 		3	|	419	|	10.90%
[INFO ] PyDI.entitymatching.evaluation - 		4	|	341	|	8.87%
[INFO ] PyDI.entitymatching.evaluation - 		5	|	212	|	5.52%
[INFO ] PyDI.entitymatching.evaluation - 		6	|	152	|	3.95%
[INFO ] PyDI.entitymatching.evaluation - 		7	|	116	|	3.02%
[INFO ] PyDI.entitymatching.evaluation - 		8	|	71	|	1.85%
[INFO ] PyDI.entitymatching.evaluation - 		9	|	68	|	1.77%
[INFO ] PyDI.entitymatching.evaluation - 		10	|	45	|	1.17%
[INFO ] PyDI.entitymatching.evaluation - 		11	|	36	|	0.94%
[INFO ] PyDI.entitymatching.evaluation - 		12	|	33	|	0.86%
[INFO ] PyDI.entitymatching.evaluation - 		13	|	40	|	1.04%
[INFO ] PyDI.entitymatching.evaluation - 		14	|	39	|	1.01%
[INFO ] PyDI.entitymatching.evaluation - 		15	|	18	|	0.47%
[INFO ] PyDI.entitymatching.evaluation - 		16	|	12	|	0.31%
[INFO ] PyDI.entitymatching.evaluation - 		17	|	13	|	0.34%
[INFO ] PyDI.entitymatching.evaluation - 		18	|	16	|	0.42%
[INFO ] PyDI.entitymatching.evaluation - 		19	|	10	|	0.26%
[INFO ] PyDI.entitymatching.evaluation - 		20	|	8	|	0.21%
[INFO ] PyDI.entitymatching.evaluation - 		21	|	11	|	0.29%
[INFO ] PyDI.entitymatching.evaluation - 		22	|	7	|	0.18%
[INFO ] PyDI.entitymatching.evaluation - 		23	|	9	|	0.23%
[INFO ] PyDI.entitymatching.evaluation - 		24	|	6	|	0.16%
[INFO ] PyDI.entitymatching.evaluation - 		25	|	3	|	0.08%
[INFO ] PyDI.entitymatching.evaluation - 		26	|	10	|	0.26%
[INFO ] PyDI.entitymatching.evaluation - 		27	|	4	|	0.10%
[INFO ] PyDI.entitymatching.evaluation - 		28	|	6	|	0.16%
[INFO ] PyDI.entitymatching.evaluation - 		29	|	2	|	0.05%
[INFO ] PyDI.entitymatching.evaluation - 		30	|	8	|	0.21%
[INFO ] PyDI.entitymatching.evaluation - 		31	|	8	|	0.21%
[INFO ] PyDI.entitymatching.evaluation - 		32	|	3	|	0.08%
[INFO ] PyDI.entitymatching.evaluation - 		33	|	2	|	0.05%
[INFO ] PyDI.entitymatching.evaluation - 		34	|	6	|	0.16%
[INFO ] PyDI.entitymatching.evaluation - 		35	|	2	|	0.05%
[INFO ] PyDI.entitymatching.evaluation - 		36	|	7	|	0.18%
[INFO ] PyDI.entitymatching.evaluation - 		37	|	1	|	0.03%
[INFO ] PyDI.entitymatching.evaluation - 		38	|	1	|	0.03%
[INFO ] PyDI.entitymatching.evaluation - 		39	|	4	|	0.10%
[INFO ] PyDI.entitymatching.evaluation - 		40	|	3	|	0.08%
[INFO ] PyDI.entitymatching.evaluation - 		41	|	3	|	0.08%
[INFO ] PyDI.entitymatching.evaluation - 		42	|	3	|	0.08%
[INFO ] PyDI.entitymatching.evaluation - 		43	|	2	|	0.05%
[INFO ] PyDI.entitymatching.evaluation - 		44	|	3	|	0.08%
[INFO ] PyDI.entitymatching.evaluation - 		45	|	1	|	0.03%
[INFO ] PyDI.entitymatching.evaluation - 		46	|	2	|	0.05%
[INFO ] PyDI.entitymatching.evaluation - 		47	|	1	|	0.03%
[INFO ] PyDI.entitymatching.evaluation - 		48	|	1	|	0.03%
[INFO ] PyDI.entitymatching.evaluation - 		49	|	3	|	0.08%
[INFO ] PyDI.entitymatching.evaluation - 		50	|	2	|	0.05%
[INFO ] PyDI.entitymatching.evaluation - 		51	|	2	|	0.05%
[INFO ] PyDI.entitymatching.evaluation - 		53	|	1	|	0.03%
[INFO ] PyDI.entitymatching.evaluation - 		54	|	1	|	0.03%
[INFO ] PyDI.entitymatching.evaluation - 		57	|	2	|	0.05%
[INFO ] PyDI.entitymatching.evaluation - 		58	|	1	|	0.03%
[INFO ] PyDI.entitymatching.evaluation - 		59	|	2	|	0.05%
[INFO ] PyDI.entitymatching.evaluation - 		61	|	1	|	0.03%
[INFO ] PyDI.entitymatching.evaluation - 		62	|	1	|	0.03%
[INFO ] PyDI.entitymatching.evaluation - 		63	|	2	|	0.05%
[INFO ] PyDI.entitymatching.evaluation - 		65	|	1	|	0.03%
[INFO ] PyDI.entitymatching.evaluation - 		70	|	3	|	0.08%
[INFO ] PyDI.entitymatching.evaluation - 		74	|	2	|	0.05%
[INFO ] PyDI.entitymatching.evaluation - 		82	|	1	|	0.03%
[INFO ] PyDI.entitymatching.evaluation - 		83	|	2	|	0.05%
[INFO ] PyDI.entitymatching.evaluation - 		84	|	3	|	0.08%
[INFO ] PyDI.entitymatching.evaluation - 		97	|	2	|	0.05%
[INFO ] PyDI.entitymatching.evaluation - 		100	|	1	|	0.03%
[INFO ] PyDI.entitymatching.evaluation - 		105	|	1	|	0.03%
[INFO ] PyDI.entitymatching.evaluation - 		106	|	1	|	0.03%
[INFO ] PyDI.entitymatching.evaluation - 		112	|	2	|	0.05%
[INFO ] PyDI.entitymatching.evaluation - 		113	|	2	|	0.05%
[INFO ] PyDI.entitymatching.evaluation - 		117	|	1	|	0.03%
[INFO ] PyDI.entitymatching.evaluation - 		127	|	1	|	0.03%
[INFO ] PyDI.entitymatching.evaluation - 		129	|	1	|	0.03%
[INFO ] PyDI.entitymatching.evaluation - 		137	|	1	|	0.03%
[INFO ] PyDI.entitymatching.evaluation - 		150	|	1	|	0.03%
[INFO ] PyDI.entitymatching.evaluation - 		157	|	1	|	0.03%
[INFO ] PyDI.entitymatching.evaluation - 		160	|	1	|	0.03%
[INFO ] PyDI.entitymatching.evaluation - 		176	|	1	|	0.03%
[INFO ] PyDI.entitymatching.evaluation - 		179	|	1	|	0.03%
[INFO ] PyDI.entitymatching.evaluation - 		180	|	1	|	0.03%
[INFO ] PyDI.entitymatching.evaluation - 		184	|	1	|	0.03%
[INFO ] PyDI.entitymatching.evaluation - 		203	|	1	|	0.03%
[INFO ] PyDI.entitymatching.evaluation - 		233	|	1	|	0.03%
[INFO ] PyDI.entitymatching.evaluation - 		237	|	1	|	0.03%
[INFO ] PyDI.entitymatching.evaluation - 		254	|	1	|	0.03%
[INFO ] PyDI.entitymatching.evaluation - 		264	|	1	|	0.03%
[INFO ] PyDI.entitymatching.evaluation - 		391	|	1	|	0.03%
[INFO ] PyDI.entitymatching.evaluation - 		483	|	1	|	0.03%
[INFO ] PyDI.entitymatching.evaluation - 		516	|	1	|	0.03%
[INFO ] PyDI.entitymatching.evaluation - 		558	|	1	|	0.03%
[INFO ] PyDI.entitymatching.evaluation - 		720	|	1	|	0.03%
[INFO ] PyDI.entitymatching.evaluation - 		1044	|	1	|	0.03%
[INFO ] PyDI.entitymatching.evaluation - 		1158	|	1	|	0.03%
[INFO ] root - Cluster size distribution written to /Users/onurcanmemis/Desktop/web-data-integration-team-project/output/cluster_analysis/cluster_size_distribution.csv

### ML Matching Evaluation
#### Playtime -> Metacritic

In [46]:
eval_p2m = EntityMatchingEvaluator.evaluate_matching(
                correspondences=correspondences_p2m,
                test_pairs=test_p2m,
                out_dir=BLOCK_EVAL_DIR,
            )

display(eval_p2m)

[INFO ] root - Confusion Matrix:
[INFO ] root -   True Positives:  93
[INFO ] root -   True Negatives:  51
[INFO ] root -   False Positives: 4
[INFO ] root -   False Negatives: 0
[INFO ] root - Performance Metrics:
[INFO ] root -   Accuracy:  0.973
[INFO ] root -   Precision: 0.959
[INFO ] root -   Recall:    1.000
[INFO ] root -   F1-Score:  0.979

{'precision': 0.9587628865979382,
 'recall': 1.0,
 'f1': 0.9789473684210526,
 'accuracy': 0.972972972972973,
 'true_positives': 93,
 'false_positives': 4,
 'false_negatives': 0,
 'true_negatives': 51,
 'threshold_used': 0.0,
 'total_correspondences': 61166,
 'filtered_correspondences': 61166,
 'evaluation_timestamp': '2025-11-29T13:59:29.483947',
 'output_files': ['/Users/onurcanmemis/Desktop/web-data-integration-team-project/output/blocking_evaluation/matching_evaluation_summary.json',
  '/Users/onurcanmemis/Desktop/web-data-integration-team-project/output/blocking_evaluation/matching_detailed_results.csv']}

#### Playtime -> Sales

In [47]:
eval_p2s = EntityMatchingEvaluator.evaluate_matching(
                correspondences=correspondences_p2s,
                test_pairs=test_p2s,
                out_dir=BLOCK_EVAL_DIR,
            )

display(eval_p2s)

[INFO ] root - Confusion Matrix:
[INFO ] root -   True Positives:  88
[INFO ] root -   True Negatives:  52
[INFO ] root -   False Positives: 2
[INFO ] root -   False Negatives: 7
[INFO ] root - Performance Metrics:
[INFO ] root -   Accuracy:  0.940
[INFO ] root -   Precision: 0.978
[INFO ] root -   Recall:    0.926
[INFO ] root -   F1-Score:  0.951

{'precision': 0.9777777777777777,
 'recall': 0.9263157894736842,
 'f1': 0.9513513513513514,
 'accuracy': 0.9395973154362416,
 'true_positives': 88,
 'false_positives': 2,
 'false_negatives': 7,
 'true_negatives': 52,
 'threshold_used': 0.0,
 'total_correspondences': 54402,
 'filtered_correspondences': 54402,
 'evaluation_timestamp': '2025-11-29T13:59:32.215382',
 'output_files': ['/Users/onurcanmemis/Desktop/web-data-integration-team-project/output/blocking_evaluation/matching_evaluation_summary.json',
  '/Users/onurcanmemis/Desktop/web-data-integration-team-project/output/blocking_evaluation/matching_detailed_results.csv']}

In [48]:
from PyDI.entitymatching import MaximumBipartiteMatching, StableMatching

# We are using Maxmimum Bipartite Matching to refine results to 1:1 matches
clusterer = MaximumBipartiteMatching()
mbm_correspondences_p2m = clusterer.cluster(correspondences_p2m)
mbm_correspondences_p2s = clusterer.cluster(correspondences_p2s)

[INFO ] root - Filtered correspondences: 61166 -> 61166 (threshold=0.0)
[INFO ] root - Maximum bipartite matching: 61166 -> 12238
[INFO ] root - MaximumBipartiteMatching: 61166 -> 12238 correspondences
[INFO ] root - MaximumBipartiteMatching: 37402 -> 24476 entities
[INFO ] root - Filtered correspondences: 54402 -> 54402 (threshold=0.0)
[INFO ] root - Maximum bipartite matching: 54402 -> 10572
[INFO ] root - MaximumBipartiteMatching: 54402 -> 10572 correspondences
[INFO ] root - MaximumBipartiteMatching: 28503 -> 21144 entities

In [49]:
eval_p2m = EntityMatchingEvaluator.evaluate_matching(
                correspondences=mbm_correspondences_p2m,
                test_pairs=test_p2m,
                out_dir=BLOCK_EVAL_DIR,
            )

display(eval_p2m)

[INFO ] root - Confusion Matrix:
[INFO ] root -   True Positives:  57
[INFO ] root -   True Negatives:  55
[INFO ] root -   False Positives: 0
[INFO ] root -   False Negatives: 36
[INFO ] root - Performance Metrics:
[INFO ] root -   Accuracy:  0.757
[INFO ] root -   Precision: 1.000
[INFO ] root -   Recall:    0.613
[INFO ] root -   F1-Score:  0.760

{'precision': 1.0,
 'recall': 0.6129032258064516,
 'f1': 0.76,
 'accuracy': 0.7567567567567568,
 'true_positives': 57,
 'false_positives': 0,
 'false_negatives': 36,
 'true_negatives': 55,
 'threshold_used': 0.0,
 'total_correspondences': 12238,
 'filtered_correspondences': 12238,
 'evaluation_timestamp': '2025-11-29T13:59:37.928054',
 'output_files': ['/Users/onurcanmemis/Desktop/web-data-integration-team-project/output/blocking_evaluation/matching_evaluation_summary.json',
  '/Users/onurcanmemis/Desktop/web-data-integration-team-project/output/blocking_evaluation/matching_detailed_results.csv']}

In [50]:
eval_p2s = EntityMatchingEvaluator.evaluate_matching(
                correspondences=mbm_correspondences_p2s,
                test_pairs=test_p2s,
                out_dir=BLOCK_EVAL_DIR,
            )

display(eval_p2s)

[INFO ] root - Confusion Matrix:
[INFO ] root -   True Positives:  54
[INFO ] root -   True Negatives:  54
[INFO ] root -   False Positives: 0
[INFO ] root -   False Negatives: 41
[INFO ] root - Performance Metrics:
[INFO ] root -   Accuracy:  0.725
[INFO ] root -   Precision: 1.000
[INFO ] root -   Recall:    0.568
[INFO ] root -   F1-Score:  0.725

{'precision': 1.0,
 'recall': 0.5684210526315789,
 'f1': 0.7248322147651006,
 'accuracy': 0.7248322147651006,
 'true_positives': 54,
 'false_positives': 0,
 'false_negatives': 41,
 'true_negatives': 54,
 'threshold_used': 0.0,
 'total_correspondences': 10572,
 'filtered_correspondences': 10572,
 'evaluation_timestamp': '2025-11-29T13:59:38.398294',
 'output_files': ['/Users/onurcanmemis/Desktop/web-data-integration-team-project/output/blocking_evaluation/matching_evaluation_summary.json',
  '/Users/onurcanmemis/Desktop/web-data-integration-team-project/output/blocking_evaluation/matching_detailed_results.csv']}

## Cluster Comparison

In [93]:
import pandas as pd

def summarize_cluster_table(df):
    """
    df columns:
      - 'cluster_size'
      - 'frequency'
      - 'percentage'  # already weighted, sums to ~100

    Returns:
      - pct_gt3: percentage of mass in clusters with size > 3
      - avg_size: average cluster size (weighted)
      - max_size: maximum observed cluster size
    """

    # % of clusters with size > 3 (already weighted via 'percentage')
    pct_gt3 = df.loc[df['cluster_size'] > 3, 'percentage'].sum()

    # weighted average cluster size using percentages
    weighted_avg_size = (df['cluster_size'] * df['percentage']).sum() / 100.0
    avg_size= df['cluster_size'].mean()
    # maximum cluster size
    max_size = df['cluster_size'].max()

    return {
        "weighted_avg_size": round(weighted_avg_size, 2),
        "avg_size": round(avg_size, 2),
        "max_size": int(max_size),
        "%_clusters_gt3": round(pct_gt3, 2),
    }

In [96]:
display(summarize_cluster_table(cluster_distribution_p2m_rb_1))
display(summarize_cluster_table(cluster_distribution_p2s_rb_1))

{'weighted_avg_size': np.float64(3.03),
 'avg_size': np.float64(40.57),
 'max_size': 306,
 '%_clusters_gt3': np.float64(16.71)}

{'weighted_avg_size': np.float64(3.81),
 'avg_size': np.float64(37.6),
 'max_size': 310,
 '%_clusters_gt3': np.float64(25.36)}

In [97]:
display(summarize_cluster_table(cluster_distribution_p2m_rb_2))
display(summarize_cluster_table(cluster_distribution_p2s_rb_2))

{'weighted_avg_size': np.float64(2.04),
 'avg_size': np.float64(4.5),
 'max_size': 7,
 '%_clusters_gt3': np.float64(0.75)}

{'weighted_avg_size': np.float64(2.05),
 'avg_size': np.float64(5.0),
 'max_size': 8,
 '%_clusters_gt3': np.float64(1.02)}

In [98]:
display(summarize_cluster_table(cluster_distribution_p2m_ml_1))
display(summarize_cluster_table(cluster_distribution_p2s_ml_1))

{'weighted_avg_size': np.float64(2.05),
 'avg_size': np.float64(4.5),
 'max_size': 7,
 '%_clusters_gt3': np.float64(0.93)}

{'weighted_avg_size': np.float64(2.12),
 'avg_size': np.float64(5.5),
 'max_size': 9,
 '%_clusters_gt3': np.float64(2.48)}

In [99]:
display(summarize_cluster_table(cluster_distribution_p2m_ml_2))
display(summarize_cluster_table(cluster_distribution_p2s_ml_2))

{'weighted_avg_size': np.float64(6.14),
 'avg_size': np.float64(55.51),
 'max_size': 203,
 '%_clusters_gt3': np.float64(58.25)}

{'weighted_avg_size': np.float64(7.41),
 'avg_size': np.float64(114.41),
 'max_size': 1158,
 '%_clusters_gt3': np.float64(36.71)}